### ISSUE TITLE
Render DOAP files in tabular view

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1005]
Hi,

I would like to suggest to render existing DOAP files in a tabular format. I think that could be a nice thing

**Comment by Echolon** [comment]
- Render in complete xep list
- Render default view which only shows compliance xeps

**Comment by Echolon** [comment]
The recent work from kikuchiyo in the CommTeam chat show what I was intending with this suggestion.

**Comment by wurstsalat3000** [comment]
Rendered XEP lists and compliance data is now available. Example: https://xmpp.org/software/clients/conversations/
