### ISSUE TITLE
Update Board and Council page

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1011]
Hey @agnauck,

would you be fine to also update the webpage?

https://xmpp.org/about/xmpp-standards-foundation/#board

File: https://github.com/xsf/xmpp.org/blob/master/content/about/xmpp-standards-foundation.md

**Comment by agnauck** [comment]
yes I will work on this next

**Comment by wurstsalat3000** [comment]
@agnauck any news?

**Comment by agnauck** [comment]
This was done after the annual election. Let me know when smth is missing. Otherwise we can close this issue,

**Comment by Echolon** [comment]
I assume everything is set
