### ISSUE TITLE
Extensions only sortable on name

### ISSUE THREAD

**Issue by intosi** [xsf/xmpp.org#103]
Would be nice if the extensions could be sorted on any column, like the old page.

**Comment by winfried** [comment]
> Would be nice if the extensions could be sorted on any column, like the
> old page.

The table on http://xmpp.org/xmpp-protocols/xmpp-extensions/ is
server-side included from the automated build process of XEPs. Build.py
also generates such a table, so the same infrastructure can be used.

**Comment by stpeter** [comment]
Can't we just continue to use the sorttable.js widget?
