### ISSUE TITLE
XMPP Subreddit r/xmpp: Updates

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1039]
Hi @neustradamus,

can you do some things in the sub-reddit please?

Rename in the headbar:

- Website --> XSF Website
- Github --> XSF Github
- Facebook --> Facebook (unofficial)
- Add Clients and Servers we list on the website
- Maybe add XMPP Work (www.xmpp.work)

On the right, can we add more tags such as "realtime communication", "xmpp", "jabber" "messaging"?

Thanks for posting the news and more.

**Comment by wurstsalat3000** [comment]
@Neustradamus any update?

**Comment by Neustradamus** [comment]
@wurstsalat3000: Done the same day, seen with @Echolon and no more links can be added.

**Comment by wurstsalat3000** [comment]
@Echolon ?

**Comment by wurstsalat3000** [comment]
@Echolon can this one be closed?

**Comment by Echolon** [comment]
I need to revisit this. please leave it open until then

**Comment by wurstsalat3000** [comment]
It's been a year ;) any update?

**Comment by Neustradamus** [comment]
https://github.com/xsf/xmpp.org/issues/1039#issuecomment-1008116339
