### ISSUE TITLE
xmpp.work: Add information about spoken languages to service providers

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1042]
I think adding information what language consulting or developing can cover apart from English is an interesting measure can be a nice extra to advertise a service.

**Comment by wurstsalat3000** [comment]
Service providers are not listed anymore, see #1241

**Comment by bleonard252** [comment]
xmpp.work is not managed by the XSF, it seems to be managed by Ignite Realtime.

**Comment by guusdk** [comment]
It is not managed by Ignite Realtime, it is managed by me, under the umbrella of my company, GoodBytes. I'm also a member of Ignite Realtime, but that's separate from xmpp.work

**Comment by Echolon** [comment]
Yes, and in general I think its a good platform here to discuss if there is anything related.
