### ISSUE TITLE
New Site dead/broken links 

### ISSUE THREAD

**Issue by bear** [xsf/xmpp.org#107]
please just add them here until I get done

**Comment by ralphm** [comment]
http://xmpp.org/council

**Comment by intosi** [comment]
Rendered XEPs, e.g. http://www.xmpp.org/extensions/xep-0313.html

**Comment by Kev** [comment]
http://xmpp.org/extensions.html <http://xmpp.org/extensions.html>

**Comment by dittos** [comment]
http://xmpp.org/schemas/streamerror.xsd

**Comment by Kev** [comment]
http://xmpp.org/about-xmpp/xsf/xsf-mission/ <http://xmpp.org/about-xmpp/xsf/xsf-mission/>
http://xmpp.org/about-xmpp/xsf/xsf-roadmap/ <http://xmpp.org/about-xmpp/xsf/xsf-roadmap/>
http://xmpp.org/about-xmpp/xsf/xsf-source-control/ <http://xmpp.org/about-xmpp/xsf/xsf-source-control/>
http://xmpp.org/participate/become-a-member/ <http://xmpp.org/participate/become-a-member/>
http://xmpp.org/participate/become-a-member/the-xsf-communication-team/ <http://xmpp.org/participate/become-a-member/the-xsf-communication-team/>
http://xmpp.org/participate/become-a-member/the-xsf-infrastructure-team/ <http://xmpp.org/participate/become-a-member/the-xsf-infrastructure-team/>
http://xmpp.org/about-xmpp/xsf/xsf-financial-summary/ <http://xmpp.org/about-xmpp/xsf/xsf-financial-summary/>
http://xmpp.org/about-xmpp/xsf/xsf-organizational-documents/ <http://xmpp.org/about-xmpp/xsf/xsf-organizational-documents/>
http://xmpp.org/xsf/xsf-people/ <http://xmpp.org/xsf/xsf-people/>
http://xmpp.org/participate/contact-us/ <http://xmpp.org/participate/contact-us/>
http://xmpp.org/about-xmpp/xsf/the-xsf-board-of-directors/ <http://xmpp.org/about-xmpp/xsf/the-xsf-board-of-directors/>
http://xmpp.org/about/wg-charter.txt <http://xmpp.org/about/wg-charter.txt>
http://xmpp.org//about-xmpp/technology-overview/pubsub/ <http://xmpp.org//about-xmpp/technology-overview/pubsub/>
http://xmpp.org//about-xmpp/technology-overview/muc/ <http://xmpp.org//about-xmpp/technology-overview/muc/>
http://xmpp.org//about-xmpp/technology-overview/jingle/ <http://xmpp.org//about-xmpp/technology-overview/jingle/>
http://xmpp.org//about-xmpp/technology-overview/core/ <http://xmpp.org//about-xmpp/technology-overview/core/>
http://xmpp.org//about-xmpp/technology-overview/bosh/ <http://xmpp.org//about-xmpp/technology-overview/bosh/>
http://xmpp.org/about-xmpp/xsf/jabber-trademark/ <http://xmpp.org/about-xmpp/xsf/jabber-trademark/>
http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-9/ <http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-9/>
http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-8/ <http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-8/>
http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-7/ <http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-7/>
http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-6/ <http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-6/>
http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-5/ <http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-5/>
http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-4/ <http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-4/>
http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-3/ <http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-3/>
http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-2/ <http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-2/>
http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-1/ <http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-1/>
http://xmpp.org/participate/the-xmpp-summit/ <http://xmpp.org/participate/the-xmpp-summit/>
http://xmpp.org/xmpp-software/servers/ <http://xmpp.org/xmpp-software/servers/>
http://xmpp.org/xmpp-software/libraries/ <http://xmpp.org/xmpp-software/libraries/>
http://xmpp.org/xmpp-software/clients/ <http://xmpp.org/xmpp-software/clients/>
http://xmpp.org/xmpp-software/ <http://xmpp.org/xmpp-software/>
http://xmpp.org/about-xmpp/technology-overview/ <http://xmpp.org/about-xmpp/technology-overview/>
http://xmpp.org/schemas/xhtml-im-model.xsd <http://xmpp.org/schemas/xhtml-im-model.xsd>
http://xmpp.org/schemas/stanzaerror.xsd <http://xmpp.org/schemas/stanzaerror.xsd>
http://xmpp.org/schemas/jabber-server.xsd <http://xmpp.org/schemas/jabber-server.xsd>
http://xmpp.org/schemas/jabber-client.xsd <http://xmpp.org/schemas/jabber-client.xsd>
http://xmpp.org/schemas/activity.xsd <http://xmpp.org/schemas/activity.xsd>
http://xmpp.org/resources/schemas/ <http://xmpp.org/resources/schemas/>
http://xmpp.org/resources/registrar/ <http://xmpp.org/resources/registrar/>
http://xmpp.org/registrar/si-profiles.html <http://xmpp.org/registrar/si-profiles.html>
http://xmpp.org/registrar/nodes.html <http://xmpp.org/registrar/nodes.html>
http://xmpp.org/xmpp-protocols/protocol-namespaces/ <http://xmpp.org/xmpp-protocols/protocol-namespaces/>
http://xmpp.org/about-xmpp/xsf/xsf-member-list/ <http://xmpp.org/about-xmpp/xsf/xsf-member-list/>
http://xmpp.org/about-xmpp/history/the-jabber-project/ <http://xmpp.org/about-xmpp/history/the-jabber-project/>
http://xmpp.org/about-xmpp/history/ <http://xmpp.org/about-xmpp/history/>
http://xmpp.org/about-xmpp/xsf/xsf-ipr-policy/ <http://xmpp.org/about-xmpp/xsf/xsf-ipr-policy/>
http://xmpp.org/about-xmpp/xsf/xsf-people/ <http://xmpp.org/about-xmpp/xsf/xsf-people/>
http://xmpp.org/extensions/attic/ <http://xmpp.org/extensions/attic/>
http://xmpp.org/xmpp-protocols/internet-drafts/ <http://xmpp.org/xmpp-protocols/internet-drafts/>
http://xmpp.org/about-xmpp/xsf/xsf-bylaws/ <http://xmpp.org/about-xmpp/xsf/xsf-bylaws/>
http://xmpp.org/participate/discuss-xmpp/ <http://xmpp.org/participate/discuss-xmpp/>
http://xmpp.org/about-xmpp/xsf/xmpp-council/policies-and-procedures/ <http://xmpp.org/about-xmpp/xsf/xmpp-council/policies-and-procedures/>
http://xmpp.org/about-xmpp/xsf/xmpp-council/ <http://xmpp.org/about-xmpp/xsf/xmpp-council/>
http://xmpp.org/resources/certificates/ <http://xmpp.org/resources/certificates/>
http://xmpp.org/sponsor/ <http://xmpp.org/sponsor/>
http://xmpp.org/about-xmpp/xsf/website-credits/ <http://xmpp.org/about-xmpp/xsf/website-credits/>
http://xmpp.org/resources/books/ <http://xmpp.org/resources/books/>
http://xmpp.org/about-xmpp/ <http://xmpp.org/about-xmpp/>

**Comment by winfried** [comment]
http://xmpp.org/uses/iot/bindings
http://xmpp.org/uses/iot/patterns
http://xmpp.org/uses/iot/things
http://xmpp.org/uses/iot/provisioning
http://xmpp.org/uses/iot/scalability
http://xmpp.org/uses/iot/interoperability

**Comment by andrey-utkin** [comment]
Please consider URLs linked from other Jabber-related sites. This thing is not something to be taken lightly.
http://xmpp.org/extensions/xeps.xml which was known to work, doesn't anymore.
https://prosody.im/doc/xeplist - the links in the bottom of list give 404, e.g. https://xmpp.org/extensions/xep-0326.html

**Comment by ashward** [comment]
All the sponsor pages are 404ing:
http://xmpp.org/sponsors/coversant
http://xmpp.org/sponsors/erlang-solutions
etc...

**Comment by xnyhps** [comment]
https://xmpp.org/resources/security-notices/uncontrolled-resource-consumption-with-highly-compressed-xmpp-stanzas/

**Comment by intosi** [comment]
The reported issues so far have been processed, checked, and already partially fixed or temporarily worked around.  If you find more, keep 'em coming.

**Comment by B-Kell** [comment]
For https://xmpp.org/software/libraries.html
https://github.com/svishnuv/Ubeity Ubeity
jabber-net link is dead, I don't know the right fork
The other C# ones are OK

**Comment by ashward** [comment]
http://xmpp.org/extensions/xep-README.html

**Comment by Neustradamus** [comment]
There is a long time I have checked a list to stpeter, maybe good to look the old configuration with redirections.

**Comment by bear** [comment]
(moved from issue #116 )
The page is missing: https://xmpp.org/contact

On https://xmpp.org/community/membership.html, "here" : https://xmpp.org/community/wiki.xmpp.org/web/Membership_Applications must be http://wiki.xmpp.org/web/Membership_Applications

**Comment by bndw** [comment]
All of the RFC links on https://xmpp.org/about/technology-overview.html are broken

**Comment by petmue** [comment]
Recursive link: http://xmpp.org/extensions/all.shtml on http://xmpp.org/extensions/

**Comment by horazont** [comment]
https://xmpp.org/registrar/si-profiles.html (from the comment above)
https://xmpp.org/registrar/shim.html (linked from xep-0131 for example)

Those are still dead.

**Comment by horazont** [comment]
While I was at it, I threw a shellscript on that long list of URLs. It reports the following still broken:

```
http://xmpp.org/about-xmpp/xsf/xsf-financial-summary/ ... ERROR 404: Not Found. fail! retcode=8
http://xmpp.org/about/wg-charter.txt ... ERROR 404: Not Found. fail! retcode=8
http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-9/ ... ERROR 404: Not Found. fail! retcode=8
http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-8/ ... ERROR 404: Not Found. fail! retcode=8
http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-7/ ... ERROR 404: Not Found. fail! retcode=8
http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-6/ ... ERROR 404: Not Found. fail! retcode=8
http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-5/ ... ERROR 404: Not Found. fail! retcode=8
http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-4/ ... ERROR 404: Not Found. fail! retcode=8
http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-3/ ... ERROR 404: Not Found. fail! retcode=8
http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-2/ ... ERROR 404: Not Found. fail! retcode=8
http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-1/ ... ERROR 404: Not Found. fail! retcode=8
http://xmpp.org/resources/registrar/ ... ERROR 404: Not Found. fail! retcode=8
http://xmpp.org/registrar/si-profiles.html ... ERROR 404: Not Found. fail! retcode=8
http://xmpp.org/registrar/nodes.html ... ERROR 404: Not Found. fail! retcode=8
http://xmpp.org/xmpp-protocols/protocol-namespaces/ ... ERROR 404: Not Found. fail! retcode=8
http://xmpp.org/about-xmpp/xsf/xsf-bylaws/ ... ERROR 404: Not Found. fail! retcode=8
http://xmpp.org/about-xmpp/xsf/xmpp-council/policies-and-procedures/ ... ERROR 404: Not Found. fail! retcode=8
http://xmpp.org/resources/certificates/ ... ERROR 404: Not Found. fail! retcode=8
http://xmpp.org/resources/books/ ... ERROR 404: Not Found. fail! retcode=8
```

Shellscript for future reference:
```
#!/bin/bash
URL="$1"
set -o pipefail
echo -n "$URL ... "
wget -O/dev/null "$URL" 2>&1 | (grep -Po 'ERROR [0-9]+.*' || true) | tr -d '\n' && echo "ok!" || echo " fail! retcode=$?"
```

(best used with ``xargs -n1``)

**Comment by andrey-utkin** [comment]
http://xmpp.org/registrar/disco-categories.html

**Comment by bear** [comment]
I've created a new list of 404s that the web site is showing.  We are going to close this issue and open a new one to help reduce some of the clutter.
