### ISSUE TITLE
Newsletter: Highlight last publication in the general Newsletter page

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1070]
I think a better representation for newcomer should be highlighted here.

![Screenshot_20220206_114844](https://user-images.githubusercontent.com/29168011/152677354-be255148-9d42-44e4-9c19-796847398ff5.png)

**Comment by wurstsalat3000** [comment]
@Echolon what do you have in mind here?

**Comment by Echolon** [comment]
Show the latest release (as below) and have the "read online here" maybe as a centered header or bigger than now?

![Screenshot_20220223_224115](https://user-images.githubusercontent.com/29168011/155413613-86802c43-bf64-47ad-8c07-e4202b45d5b7.png)

**Comment by Echolon** [comment]
Maybe only the header
