### ISSUE TITLE
Idea: Automate monthly newsletter PR creation

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1077]
Any suggestions if that could be a thing?

**Comment by wurstsalat3000** [comment]
Which part would you want to automate?

**Comment by Echolon** [comment]
What I am doing each month here as inital step: https://github.com/xsf/xmpp.org/pull/1093/commits/cf9762a226fb2851e4a44a7d9319a307ab72d454

**Comment by wurstsalat3000** [comment]
I don't think this should be automated, since it's a good thing to have someone's eyes on what's actually being copied over.

**Comment by wurstsalat3000** [comment]
I added a newsletter PR template in 95bd118d3da3beadc5641856407e76a489952cd8 but I don't think there can be much more automation here. Closing for now ;)
