### ISSUE TITLE
XMPP Providers project on https://xmpp.org

### ISSUE THREAD

**Issue by melvo** [xsf/xmpp.org#1083]
[XMPP Providers](https://invent.kde.org/melvo/xmpp-providers) makes onboarding easier. Filtered provider lists are already [hosted on data.xmpp.net](https://github.com/xsf/infrastructure/issues/14).

Currently, there is only the mentioned project site. We think that an overview / welcome page on https://xmpp.org could reach more people. Thus, we suggest to create a page with the following content:

1. Introduction for everybody
2. Detailed section for users describing that they can use specific clients already integrating XMPP Providers or search providers on the web page (see point 4)
3. Short section for server admins / operators and client developers with a link to the project site
4. Table listing all providers automatically retrieved from the lists on data.xmpp.net (including filtering, sorting, searching, description why a provider is in a specific [category](https://invent.kde.org/melvo/xmpp-providers#categories) and how to improve that)
5. Form for submitting new providers as an alternative to directly creating a [merge request](https://invent.kde.org/melvo/xmpp-providers/-/merge_requests)

**Comment by mwild1** [comment]
[Moved to xsf/xmpp.org](https://github.com/xsf/xmpp.org/issues/1083)

**Comment by Echolon** [comment]
We discuss, that we want to respect neutrality of XSF and just render whats in there.

so a "simple" table could do the job. Maybe there are some other nice rendering options Im not away of.

anyway - I know you have a lot of other priorities and other focus atm but could that be something you could do for us? @wurstsalat3000 

or is it hard to take the XEP table example rendering?

anyway dont - we plan to add one or more parameters first, so no rush

**Comment by Echolon** [comment]
> This shouldn't be too hard to implement.
> 
> Did you discuss this on [xsf@muc.xmpp.org](mailto:xsf@muc.xmpp.org) ?

No yet - I think we should @melvo

**Comment by melvo** [comment]
@Echolon Yes, we can discuss that topic.

There is a [new website](/xsf/xmpp-providers-website) for presenting the providers and their results. Thus, I suggest to only link from https://xmpp.org/getting-started/ to the new website and cover [all mentioned ideas](1083#issue-1147990117) there.

**Comment by melvo** [comment]
We have https://github.com/xsf/xmpp-providers-website and #1113 now.
