### ISSUE TITLE
move items from old vhost / path

### ISSUE THREAD

**Issue by bear** [xsf/xmpp.org#109]
robots.txt
prettify.css
prettify.js
favicon.ico

(any others?)

**Comment by guusdk** [comment]
@bear, I'm not sure what needs to be done here. Can you elaborate?

**Comment by wurstsalat3000** [comment]
@bear any news? We have robobts.txt and favicon.ico available (no trace of prettify.css/.js, not sure what they should be for).

**Comment by wurstsalat3000** [comment]
@mwild1 I guess this can be closed now?
