### ISSUE TITLE
Give me the ability to assign issues :)

### ISSUE THREAD

**Issue by adambrault** [xsf/xmpp.org#11]
I think you have this access @imaginator?

**Comment by adambrault** [comment]
And to be able to push what I have.

**Comment by bear** [comment]
@adambrault has a pending invitation to the website build team

**Comment by imaginator** [comment]
@adambrault - I had set you as an admin of the XSF group last week. Should be possible.

**Comment by bear** [comment]
closing - your on the owners team now
