### ISSUE TITLE
Tinyletter: Replace with simple maillist

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1110]
As you have heard the Tinyletter is no usable anymore. So we need to find a replacement.
I wished to have something nice, but to be honest - it's not worth it.

@stpeter suggested to make a new mail-list setup for us. I think for being a bit of old-school (but still simple to onboard) I think its fine. We talk about 300 - 600 subscribers currently.

Steps we would need to do:

- [x] Create new mail list
- [x] Discuss interface with Mailman (just link to the [subscription](https://mail.jabber.org/mailman/listinfo/standards) page?)
- [x] Discuss migration of subscribed users
  - I would simply export the list and ask @stpeter to add them to the list?
- [x] Send a first mail to the migrated accounts and offer them to unsubscribe
- [x] Set mail-list to no-reply functionality? @stpeter 

CC: @wurstsalat3000 @jcbrand @SeveFP 
FYI: @mwild1, @ralphm, @arcriley

Please vote up if you like the idea.

**Comment by Echolon** [comment]
AND it is a privacy respecting solution - what Tinyletter is NOT

**Comment by stpeter** [comment]
Once we have a decision on this I'll be happy to help with the setup. Don't forget to mention or otherwise poke me if I'm not responsive. :-)

**Comment by stpeter** [comment]
What address would you like for the list? Perhaps newsletter@xmpp.org would be fine?

**Comment by Echolon** [comment]
> What address would you like for the list? Perhaps [newsletter@xmpp.org](mailto:newsletter@xmpp.org) would be fine?

Yes, lets do this!

**Comment by stpeter** [comment]
The subscription page is at https://mail.jabber.org/mailman/listinfo/newsletter

**Comment by stpeter** [comment]
I've made @Echolon a list admin.

**Comment by stpeter** [comment]
All subscribers are modded by default (i.e., read-only).

**Comment by Echolon** [comment]
https://mail.jabber.org/mailman/listinfo/newsletter
