### ISSUE TITLE
Make extensions.md more present

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1115]
This is kind of the core product we do, but it is hidden in the top bar: https://xmpp.org/extensions/

I think we should make it its own button there.

What do you think

**Comment by Echolon** [comment]
Anyway that all could be reorganized a bit I think

Less pages are maybe also helpful

**Comment by wurstsalat3000** [comment]
![image](https://user-images.githubusercontent.com/35428560/161764700-192fecb0-9da6-4fb4-bf90-284b83f9d998.png)

That's not enough?

**Comment by Echolon** [comment]
Yes I know this.

But as the other things are present in the headline all the time, I would like to have this there too.

but if your dont like it - is fine

**Comment by wurstsalat3000** [comment]
Before adding another first level menu item, we should probably evaluate other menu items first.

I moved the 'Specifications' button to a more prominent place for now.
