### ISSUE TITLE
work.xmpp.net: move xmpp.work?

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1118]
Maybe also rebuild page?

**Comment by wurstsalat3000** [comment]
Why not keep it the way it is?

**Comment by Echolon** [comment]
@jcbrand announced:

> Hi, I'm not completely sure where to bring this up... I would like to retire the https://xmpp.work website, or alternatively hand it over to someone else who is willing to maintain it. In order for the site to be useful, it needs people to regularly post jobs, but this is not happening. In the beginning I would look for XMPP jobs and then add them to xmpp.work with the hope that eventually it wouldn't be necessary and that companies would advertise there themselves. This didn't happen unfortunately, and no new jobs are appearing there. In addition, I have to spend every other day removing spam and spam accounts. If anyone is interested in taking over the site from me, let me know, otherwise I'd like to turn it off and have the link removed from https://xmpp.org
