### ISSUE TITLE
Website: various elements do not follow dark theme

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1126]
See:

* https://xmpp.org/rfcs/#3920
![Screenshot_20220501_002247](https://user-images.githubusercontent.com/29168011/166124520-ce6ba343-422f-4af5-9e37-8baef06322cf.png)
* https://xmpp.org/newsletter/
![Screenshot_20220501_002322](https://user-images.githubusercontent.com/29168011/166124531-25e6961d-8232-4272-9d10-04a2310a350a.png)

**Comment by linkmauve** [comment]
Hi, I can’t reproduce on Firefox, everything you pointed looks correct. Do you maybe use an extension that could mess things up?

**Comment by wurstsalat3000** [comment]
Nope, I just fixed those already in 600a1d8ab8fbfbd8c9502c655fc9bdd3af77caf3 and didn't see this issue :)
