### ISSUE TITLE
Generate comparison tables from DOAP

### ISSUE THREAD

**Issue by Ppjet6** [xsf/xmpp.org#1185]
Everywhere on the web we find the kind of tables you can see here:
- https://en.wikipedia.org/wiki/Comparison_of_XMPP_clients
- https://en.wikipedia.org/wiki/Comparison_of_XMPP_server_software

That is, comparison tables about the projects themselves (license, type of client, programming language, platform, etc.), or some about features support (or rather, specs).

These tables are often hard to maintain and end-up very quickly outdated, providing wrong information on many projects. Now that DOAP is a thing, it should be possible to render these obsolete.

Surely anybody with access to DOAP information could make their own comparison tables. Maybe we can provide some minimal comparison to show off the feature and explain somewhere how to reproduce/improve? I'm not sure Wikipedia would offer such a feature though.. Maybe these pages should just disappear.

ESTIMATE: 20h

**Comment by Ppjet6** [comment]
Maybe duplicate of #585, or related at least.

**Comment by Echolon** [comment]
Possibly, let's keep both open for inspiration

**Comment by wurstsalat3000** [comment]
Current proposal is: Comparing two or more clients/servers/libraries directly.
