### ISSUE TITLE
clients.json: Fix AstraChat

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1198]
The version attribute refers to the XEP version implemented by the software. AstraChat client's added version instead. Please either remove all version attributes, or change it to the implemented XEP versions. For reference: https://linkmauve.fr/ns/xmpp-doap

Here is an example where the version attribute is set wrongly, but this affects all XEPs listed:

```xml
<implements>
<xmpp:SupportedXep>
<xmpp:xep rdf:resource="https://xmpp.org/extensions/xep-0030.html"/>
<xmpp:status>complete</xmpp:status>
<xmpp:version>1.6</xmpp:version>
</xmpp:SupportedXep>
</implements>
```

Estimate: 1h

**Comment by Echolon** [comment]
@rockliffe

**Comment by rockliffe** [comment]
Thank you for the notification, we will get both DOAPs updated.

**Comment by rockliffe** [comment]
Thanks @Echolon, we've fixed the DOAPs.

**Comment by Echolon** [comment]
Thank you!

**Comment by john-g-davies** [comment]
Hello @Echolon , please explain which version numbers, thanks.

**Comment by Echolon** [comment]
@john-g-davies yes sure.

When we talk about version numbers, we mean the XEP version number that is implemented. You can see the result for example when looking at Gajim's entry: https://xmpp.org/software/clients/gajim/

Each XEP is published an mainted in versions, for example: https://xmpp.org/extensions/xep-0470.html

**Comment by rockliffe** [comment]
@Echolon , thanks for the explanation.  I believe we already published the client and server XEP versions.  Did we make a mistake?

**Comment by wurstsalat3000** [comment]
@rockliffe AstraChat _Client_ is alright! AstraChat _Server_ doesn't supply version numbers of implemented XEPs though. That would be a nice addition! :)

See https://xmpp.org/software/servers/astrachat-xmpp-server/ [Show Supported XEPs]

**Comment by rockliffe** [comment]
I see, thanks @wurstsalat3000, we'll look into it.
