### ISSUE TITLE
[Website] Kaidan is listed as being available for Linux, macOS, Android and Windows, but is only available for Linux and Android

### ISSUE THREAD

**Issue by hazelnot** [xsf/xmpp.org#1207]

**Comment by guusdk** [comment]
@melvo is this something that needs addressing on your end?

**Comment by melvo** [comment]
Hi, Kaidan supports those platforms in general but there are currently problems building it automatically by KDE's infrastructure. However, we are already working on fixing the problems for Kaidan's next release!

**Comment by guusdk** [comment]
Ok, thanks!
