### ISSUE TITLE
RSS Feed for the Blog

### ISSUE THREAD

**Issue by haeckle** [xsf/xmpp.org#121]
Would be really nice to have the ability to subscribe to the blog-feed on the website.
Documentation for this feature on GitHub-pages is here: https://help.github.com/articles/atom-rss-feeds-for-github-pages/

**Comment by bear** [comment]
the site is only hosted on gh-pages for staging purposes, the public facing one is a static site generated using pelican...

but the point still remains you want RSS/Atom back :)

**Comment by intosi** [comment]
The feed you need is at https://xmpp.org/feeds/all.atom.xml, although it's possibly a bit unwieldly because it holds all items, not just a few most recent ones.

**Comment by haeckle** [comment]
Thanks, indeed it's a little bit to huge for normal use. The last ten posts or maybe the last year or so would be nice.

**Comment by haeckle** [comment]
Very nice! Thanks :smiley:
