### ISSUE TITLE
Create a press kit

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1231]
A press pack usually contains things like
* logos
* a brief overview of the organization
* quick facts

All designed to be easily copy/paste incorporated into articles etc.

**Comment by wurstsalat3000** [comment]
> The XMPP Standards Foundation (XSF) is an independent, nonprofit standards development organization with the mission to build an open, secure, feature-rich, federated infrastructure for real-time communication and collaboration over the Internet. We seek to achieve that goal by developing the world’s best open protocols for instant messaging, presence, and other forms of near-real-time communication, based on the IETF’s Extensible Messaging and Presence Protocol (XMPP). By “best” we mean simplest, most extensible, most powerful, most secure. Moreover, we value freedom, openness, and good technical design.
