### ISSUE TITLE
Small poll in media channels

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1238]
Besides a big poll, lets have a bit more understanding who is following us actually.

A poll could asked:

Are you a

- XMPP User
- XMPP Developer
- Organisation / Company / Institution
- Developer within Realtime Communications
- Developer from other areas
- Other

CC: @mwild1 @vanitasvitae

**Comment by cal0pteryx** [comment]
Mastodon offers **4** choices in polls ;)

**Comment by cal0pteryx** [comment]
Workshop happened recently :)
