### ISSUE TITLE
Update Twitter Profile image

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1239]
Hello,

I have no direct access to the Twitter profile from the XSF.

There for I would like to ask one from the owners to update the logo in Twitter to either
- [x] Rescale so the logo can be seen well
![image](https://user-images.githubusercontent.com/29168011/216592757-8a43c3a7-3078-4af7-8daa-e8ac18c4229e.png)

- Adapt with the Fosstodon setup: 
![image](https://user-images.githubusercontent.com/29168011/216592640-9a8c18c3-5d7b-4d77-81dd-1ac20aa3b9a5.png)

- [ ] Furthermore, the banner should be updated as well.

**Comment by Echolon** [comment]
@Kev have you had a chance on the topic?

**Comment by Neustradamus** [comment]
I have already requested several years ago.
- https://github.com/xsf/xmpp.org/issues/608

My personal version is not the current text which has been updated by @wurstsalat3000.

**Comment by Neustradamus** [comment]
Neustradamus edited on Jan 24, 2021:
```
Currently and badly:
- Twitter: https://i.ibb.co/44Zk9Th/xmpp-twitter.png
- Mastodon: https://i.ibb.co/BfJrphx/xmpp-mastodon.png

It must be:
- For Twitter and Mastodon (currently not complete): https://i.ibb.co/sFPB835/XMPP-logo.png

Mastodon:
- https://fosstodon.org/@xmpp

Twitter:
- https://twitter.com/xmpp
```

**Comment by Kev** [comment]
I have updated the profile picture (I note that the one Neustradamus supplied wasn't suitable as the background seemed to be transparent, losing the text against a dark background).

If people want a banner, someone will need to supply a banner.

**Comment by wurstsalat3000** [comment]
Thanks!

@Echolon could you use the attached logo for Mastodon as well?

![xmpp_200x200](https://user-images.githubusercontent.com/35428560/221557988-8c54d057-87e4-4678-b592-aea5b92322aa.png)

**Comment by Echolon** [comment]
@Kev many thanks!

When I comes to the banner I was just thinking of our xmpp.org tunnel picture as we have it on Mastodon already.

Is that alright?

**Comment by wurstsalat3000** [comment]
That would be one of:

* https://github.com/xsf/xmpp.org/blob/master/themes/xmpp.org/static/images/london.jpg
* https://github.com/xsf/xmpp.org/blob/master/themes/xmpp.org/static/images/london-dark.jpg

**Comment by Kev** [comment]
Banner's now london-dark.
