### ISSUE TITLE
xmpp.org/software/: Clients ordered incorrect

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1282]
See this order under All/other filter

![Screenshot_20230620_214356](https://github.com/xsf/xmpp.org/assets/29168011/d7df4a56-ecdb-4cd2-906f-2a7814dbef44)

**Comment by cal0pteryx** [comment]
That's ordered correctly depending on who you ask. Hugo orders uppercase letters before lowercase letters.
