### ISSUE TITLE
Update sponsor info: Erlang Solutions

### ISSUE THREAD

**Issue by lauracrossley** [xsf/xmpp.org#129]
I have the logo - unsure how to share.

From Erlang:

We have a new website https://www.erlang-solutions.com/, so the linking has changed there :)  

Description: 

We develop and build trusted, fault-tolerant systems that can scale massively. We’re passionate about Erlang/OTP & Elixir and we specialise in a wide range of products, on-site/remote consulting, support and mobile development to architecture/code reviews and training. We develop MongooseIM, the XMPP-based messaging platform that caters to millions of online users in high-growth sectors such as social media, gaming and telecommunications.

From startups to Fortune 100 companies, there are over 300 clients in our portfolio. Our team - over 100 specialists, works out of London, Stockholm, Krakow, Budapest, Berlin, San Francisco, Seattle and Buenos Aires

**Comment by bear** [comment]
you can add the logo to this issue or you can email it to me or just point me to the url?

**Comment by bear** [comment]
Text has been updated

**Comment by bear** [comment]
done
