### ISSUE TITLE
Add website link on top layer of software entry

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1297]
I would like to suggest to add a direct link to reach entry on the top view.

![Screenshot_20230910_174745](https://github.com/xsf/xmpp.org/assets/29168011/630eb998-8dd1-47c8-8e99-4695eea50ed8)

Currently it is required to click on 'Details'

**Comment by cal0pteryx** [comment]
Buttons / Links within `collapse` headers are not possible.

**Comment by cal0pteryx** [comment]
No
