### ISSUE TITLE
xmpp.org/software: preselection via extended URL

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#1323]
Please help with a better title :)

A user has asked me if for example the filter selection "Android" or other details can be exported as link, so they can share the respective selection with others based on the needs.

I think the idea is nice.

**Comment by cal0pteryx** [comment]
Sounds like a good idea. By default, we try to guess the user's OS, and set the category accordingly.
If query parameters are attached, we could ignore this logic and apply the query parameters instead.
