### ISSUE TITLE
Update Tigase sponsor listing and add Tygrys listing

### ISSUE THREAD

**Issue by stpeter** [xsf/xmpp.org#1333]
On behalf of the Board, this issue is here to track two updates to the sponsor pages. Details to follow.

**Comment by Echolon** [comment]
@stpeter a kind reminder

**Comment by stpeter** [comment]
@Echolon I thought you would submit a PR referencing this issue. If you want me to create the PR, let me know (but I don't have the details about Tygrys).

**Comment by Echolon** [comment]
> @Echolon I thought you would submit a PR referencing this issue. If you want me to create the PR, let me know (but I don't have the details about Tygrys).

Ah okay, I thought you wanted to do it. I can do it of course.

**Comment by Echolon** [comment]
Hi @hantu85 

can you tell us if this is still up to date? https://github.com/xsf/xmpp.org/blob/master/content/sponsors/tigase.md

Would you like to help us to write a similar text for Tygrys?
which logo do you want us to use?

**Comment by plaidroni** [comment]
Hi @stpeter, I've just submitted the PR for the addition of Tygrys to the sponsors page.

https://github.com/xsf/xmpp.org/pull/1337

Please let me know if you have any questions or concerns

**Comment by cal0pteryx** [comment]
@stpeter is there something left to do? Otherwise I'd close this issue.
