### ISSUE TITLE
PubSub Server Information

### ISSUE THREAD

**Issue by Neustradamus** [xsf/xmpp.org#1340]
Dear xmpp.org XMPP team,

It is possible to add the "PubSub Server Information" support on xmpp.org?
- https://github.com/xsf/xeps/pull/1312

cc: @guusdk.

**Comment by cal0pteryx** [comment]
xmpp.org is displayed in the network graph.

**Comment by Neustradamus** [comment]
@cal0pteryx: Excellent, thanks to the XMPP service team.
