### ISSUE TITLE
remove any analytics from the generated pages

### ISSUE THREAD

**Issue by bear** [xsf/xmpp.org#139]
we need numbers, yes, but this is a pre-emptive measure to 1) document what analytics are present and 2) find out who was looking at them.

any we do add should be iteam managed going forward

**Comment by guusdk** [comment]
I don't see "analytics" in the source of a random page that I looked at just now, but I'm not sure what to look for in the first place. Was this issue resolved?

**Comment by guusdk** [comment]
No longer an issue, according to bear via IM.
