### ISSUE TITLE
Open xeplist.xml for collaboration

### ISSUE THREAD

**Issue by avidseeker** [xsf/xmpp.org#1406]
[Checking]( https://github.com/search?q=repo%3Axsf%2Fxmpp.org%20xeplist&type=code) how the [specs table](https://xmpp.org/extensions/) is rendered: I found that hugo is using the data from https://xmpp.org/extensions/xeplist.xml to render it, which doesn't seem to be available on this repo?

**Comment by cal0pteryx** [comment]
Hi!

`xeplist.xml` is generated from the tool chain at https://github.com/xsf/xeps

Services at xmpp.org are a product of multiple repositories, all residing under the the https://github.com/xsf namespace.

**Comment by cal0pteryx** [comment]
Here is the entrypoint for generating xeplist.xml https://github.com/xsf/xeps/blob/master/Makefile#L62
