### ISSUE TITLE
Include links for implementation compliance

### ISSUE THREAD

**Issue by avidseeker** [xsf/xmpp.org#1407]
In the implementation compliance table, it might be useful to include links for the issue/discussion link. For example, I'm checking XEP-0209, and I'd like to know why was it removed from Gajim.

![image](https://github.com/xsf/xmpp.org/assets/67508272/89e73aa7-45ad-4644-baea-231939827dde)

**Comment by avidseeker** [comment]
Same goes for the table of supported XEPs by software. E.g: https://xmpp.org/software/dino/ shows a button:

"This site is organized in the open on [GitHub](https://github.com/xsf/xmpp.org). [Edit this page](https://github.com/xsf/xmpp.org/edit/master/content/software/dino.md)"

But clicking "edit this page" redirect to a non-existent page.

**Comment by cal0pteryx** [comment]
All pages under https://xmpp.org/software/ are generated automatically from each project's DOAP file. You can read about the DOAP standard here: https://xmpp.org/extensions/xep-0453.html

The standard allows for various information to be published _by the software projects_. If you view for example https://xmpp.org/software/gajim/ and open "Show supported XEPs", it lists all available XEP information for this project, which is provided _by the project_. The implementation list at https://xmpp.org/extensions/#xep-0209-implementations is also generated from that list.

xmpp.org aggregates all these infos by querying each project's DOAP file from here: https://github.com/xsf/xmpp.org/blob/master/data/software.json

There is no manual work involved here. If you would like to add info, you would have to do it at the source, meaning in a project's DOAP file :)
