### ISSUE TITLE
Link to possibly compromised site

### ISSUE THREAD

**Issue by SamWhited** [xsf/xmpp.org#148]
Firefox or my adblocker or something (I didn't stop to check) is reporting the homepage for the Araneo BOSH session manager as malicious or possibly compromised.

It is linked from [this page](https://xmpp.org/about/technology-overview.html#bosh) on xmpp.org, and should probably be removed if it's now serving malware.

I did not click through to verify this.

**Comment by petmue** [comment]
Here's are the virus total result:
https://www.virustotal.com/en/url/491fad943db573c7f23ad109d5b054dc6ee8af3e5c1e66ab1b041b038f5c94e6/analysis/1457256222/

I took the risk. It seems they have already taken the website in question arborio.bluendo.com or blog.bluendo.com (5.39.90.140) offline. The main website www.bluendo.com (91.121.227.135) is still online.

**Comment by bear** [comment]
Can one of you point me to the page where the link is (or do a PR to remove the URL temporarily?)

thanks
