### ISSUE TITLE
Pages in need of initial content

### ISSUE THREAD

**Issue by adambrault** [xsf/xmpp.org#15]
Much of this content can come from the original website.

### About

- [ ] /about/who-uses-xmpp
- [ ] /about/standards-process

### Uses

- [x] /uses
- [ ] /uses/instant-messaging
- [ ] /uses/internet-of-things
- [x] /uses/social
- [x] /uses/webrtc
- [ ] /uses/realtime-web

### Software

- [x] /software
- [x] /software/clients
- [x] /software/servers
- [x] /software/libraries
- [x] /software/projects

### Community

- [x] /community
- [x] /community/chat
- [x] /community/mailing-lists
- [x] /community/membership
- [x] /community/events
- [x] /community/sponsorship

**Comment by imaginator** [comment]
I'll write up and submit a pull request for `/uses/social`. Tracking progress in https://github.com/xsf/xmpp.org/issues/36

**Comment by adambrault** [comment]
The remaining pages listed here all have individual issues for them.
