### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by aerth** [xsf/xmpp.org#151]
Sun, 13 Mar 2016 05:19:22 UTC (expired 1 day, 4 hours ago)   EXPIRED
https://www.ssllabs.com/ssltest/analyze.html?d=xmpp.org&s=64.49.234.240

**Comment by stpeter** [comment]
Should be fixed, please verify.

**Comment by petmue** [comment]
:+1:  Now expires on 2017/03/14.

However SSLLabs says,
> This server's certificate chain is incomplete. Grade capped to B."
Extra download 	StartCom Class 1 DV Server CA

**Comment by stpeter** [comment]
Oops, server misconfiguration. I think it's fixed now.

**Comment by aerth** [comment]
## Woohoo! 
![screenshot - 03142016 - 11 02 32 pm](https://cloud.githubusercontent.com/assets/6263105/13768976/10e415a4-ea39-11e5-8fb9-4ee1c4cf87be.png)

Thanks!

**Comment by aerth** [comment]
xmpp rocks!
