### ISSUE TITLE
xmpp.org/extensions table is too narrow

### ISSUE THREAD

**Issue by tfar** [xsf/xmpp.org#158]
The table on http://xmpp.org/extensions/ is too narrow. Either the theme should be changed to allow wider content altogether, or the specific page should be wider.

**Comment by guusdk** [comment]
Perhaps the 'date' column could be dropped? That would allow for some extra room for the other columns, without requiring a theme change. I'm not sure if having a date in that table is of much added value to begin with.

**Comment by tfar** [comment]
Yeah. Let's remove all information, that'll make it even easier to work with crappy theme engine. :) I think the date column provides an easy overview on recent changes. Even with removing it there's not enough space. We really should someone who knows how the pelican stuff works and how we can have a wider page, and if that's not possible, make all pages wider.

**Comment by bear** [comment]
The extensions page is generated by the XEP tools now, it's not a part of the pelican generated items.

I'll close this and open a new ticket in that repo once I talk to the xep editors about it

**Comment by tfar** [comment]
This seems to be fixed now. Looking at http://xmpp.org/extensions/ .

**Comment by bear** [comment]
@tfar then i'll close my PR - thanks!
