### ISSUE TITLE
Plan for existing content (input, please)

### ISSUE THREAD

**Issue by adambrault** [xsf/xmpp.org#17]
## **NOTE:** _Deleting things as they get added in or other, more specific issues created for them_

We need to move existing content to the new site. But before we can do that, we need some kind of plan for what goes where. 

I've pulled down an exhaustive list of all URLs on the present xmpp.org site, then grouped and sorted by what I think we should do with them. 

I would really like input on the "misc" sections.

---
# Misc:

Not sure what to do with these.

```
http://xmpp.org/about-xmpp/xsf/xsf-ipr-policy/
http://xmpp.org/about-xmpp/xsf/xsf-people/
http://xmpp.org/author/admin/
http://xmpp.org/about-xmpp/?page_id=297
http://xmpp.org/author/stpeter/
http://xmpp.org/about-xmpp/faq/?page_id=297
http://xmpp.org/internet-drafts/attic/draft-jabber-00.txt
http://xmpp.org/internet-drafts/attic/draft-jabber-00.html
http://xmpp.org/internet-drafts/attic/draft-miller-jabber-00.txt
http://xmpp.org/internet-drafts/attic/draft-miller-jabber-00.html
http://xmpp.org/about/bof-minutes.txt
http://xmpp.org/about/wg-charter.txt
http://xmpp.org/about/ipr-notice.txt
```
# Misc XEP/Protocol supporting pages:

Not sure what to do with these.

```
http://xmpp.org/xmpp-protocols/xmpp-core/?page_id=297
http://xmpp.org/participate/become-a-member/editor-team/
http://xmpp.org/extensions/inbox/
http://xmpp.org/extensions/refs/
http://xmpp.org/xmpp-protocols/xmpp-extensions/submitting-a-xep/
```
# RFCs:

Need to make some decisions about how and where these are linked to/from. @ralphm would love to have your input.

```
http://xmpp.org/rfcs/rfc3920.html
http://xmpp.org/rfcs/rfc3921.html
http://xmpp.org/rfcs/rfc6120.html
http://xmpp.org/rfcs/rfc6121.html
http://xmpp.org/rfcs/rfc6122.html
```

**Comment by imaginator** [comment]
@bear: would you be able to run your WP->markdown script and create a pull request?

**Comment by adambrault** [comment]
@imaginator — certainly not for all of this content, right?

**Comment by imaginator** [comment]
@adambrault: I was thinking for the blog posts no?

**Comment by adambrault** [comment]
@imaginator most of this content is in wordpress, so just wanted to make it clear which part you were referring to :) It would be awesome to do this with [blog posts](https://github.com/xsf/xmpp.org/issues/7), absolutely!

**Comment by bear** [comment]
I can convert any of the wordpress content if needed but for this pass I will convert only the blog posts

**Comment by willsheward** [comment]
Reference the Misc section

http://xmpp.org/about-xmpp/xsf/xsf-ipr-policy/ - under http://xmpp.org/about-xmpp/xsf/? (incidentally this page on the existing site references itself).
http://xmpp.org/about-xmpp/xsf/xsf-people/ - under http://xmpp.org/about-xmpp/xsf/
http://xmpp.org/author/admin/ & http://xmpp.org/author/stpeter/ are both just author links for blog posts.
http://xmpp.org/about-xmpp/?page_id=297 - technology-overview?
http://xmpp.org/about-xmpp/faq/?page_id=297 - with the IPR stuff in /about-xmpp/xsf/?
http://xmpp.org/internet-drafts/attic/* - delete
http://xmpp.org/about/bof-minutes.txt - no idea
http://xmpp.org/about/wg-charter.txt - no idea
http://xmpp.org/about/ipr-notice.txt - no longer current, I think the first item in this list replaces it?

**Comment by Kev** [comment]
Simon asked me to post the rewrite rules that're in use at the moment.

rewrite	^/about/$			http://xmpp.org/about-xmpp/;
rewrite	^/about/books.shtml		http://xmpp.org/resources/books/;
rewrite	^/about/contributors.shtml	http://xmpp.org/about-xmpp/xsf/website-credits/;
rewrite	^/about/copyright.shtml		http://xmpp.org/about-xmpp/xsf/xsf-ipr-policy/;
rewrite	^/about/discuss.shtml		http://xmpp.org/participate/discuss-xmpp/;
rewrite	^/about/history.shtml		http://xmpp.org/about-xmpp/history/;
rewrite	^/about/ietf-1999.shtml		http://xmpp.org/about-xmpp/history/the-jabber-project/;
rewrite	^/about/index.shtml		http://xmpp.org/about-xmpp/;
rewrite	^/about/jabber.shtml		http://xmpp.org/about-xmpp/history/;
rewrite	^/about/reqsum.shtml		http://xmpp.org/;
rewrite	^/about/sponsors.shtml		http://xmpp.org/sponsor/;
rewrite	^/about/summary.shtml		http://xmpp.org/about-xmpp/technology-overview/;
rewrite	^/about/xmpp-simple.shtml	http://xmpp.org/;
rewrite	^/ca/$				http://xmpp.org/resources/certificates/;
rewrite	^/ca/developers.shtml		http://xmpp.org/resources/certificates/;
rewrite	^/ca/dynamic-dns.shtml		http://xmpp.org/resources/certificates/;
rewrite	^/ca/index.shtml		http://xmpp.org/resources/certificates/;
rewrite	^/ca/installation.shtml		http://xmpp.org/resources/certificates/;
rewrite	^/ca/issuance.shtml		http://xmpp.org/resources/certificates/;
rewrite	^/ca/launch.shtml		http://xmpp.org/resources/certificates/;
rewrite	^/ca/whois.shtml		http://xmpp.org/resources/certificates/;
rewrite	^/ca/wizard.shtml		http://xmpp.org/resources/certificates/;
rewrite	^/council/$			http://xmpp.org/about-xmpp/xsf/xmpp-council/;
rewrite	^/council/index.shtml		http://xmpp.org/about-xmpp/xsf/xmpp-council/;
rewrite	^/council/meetings		http://xmpp.org/about-xmpp/xsf/xmpp-council/;
rewrite	^/council/members		http://xmpp.org/participate/become-a-member/;
rewrite	^/council/policies.shtml	http://xmpp.org/about-xmpp/xsf/xmpp-council/policies-and-procedures/;
rewrite	^/council/tallies_01.shtml	http://xmpp.org/about-xmpp/xsf/xmpp-council/;
rewrite	^/council/tallies_02.shtml	http://xmpp.org/about-xmpp/xsf/xmpp-council/;
rewrite	^/council/tallies_03.shtml	http://xmpp.org/about-xmpp/xsf/xmpp-council/;
rewrite	^/council/tallies_04.shtml	http://xmpp.org/about-xmpp/xsf/xmpp-council/;
rewrite	^/council/tallies_05.shtml	http://xmpp.org/about-xmpp/xsf/xmpp-council/;
rewrite	^/council/tallies_06.shtml	http://xmpp.org/about-xmpp/xsf/xmpp-council/;
rewrite	^/council/tallies_07.shtml	http://xmpp.org/about-xmpp/xsf/xmpp-council/;
rewrite	^/council/tallies_08.shtml	http://xmpp.org/about-xmpp/xsf/xmpp-council/;
rewrite	^/council/tallies_09.shtml	http://xmpp.org/about-xmpp/xsf/xmpp-council/;
rewrite	^/council/votes.shtml		http://xmpp.org/about-xmpp/xsf/xmpp-council/;
rewrite	^/devcon			http://xmpp.org/participate/the-xmpp-summit/;
rewrite	^/discuss.html			http://xmpp.org/about/discuss.shtml;
rewrite	^/docs/bylaws.shtml		http://xmpp.org/about-xmpp/xsf/xsf-bylaws/;
rewrite	^/drafts			http://xmpp.org/internet-drafts/;
rewrite	^/extensions/attic/index.php	http://xmpp.org/extensions/attic/;
rewrite	^/extensions/$			http://xmpp.org/xmpp-protocols/xmpp-extensions/;
rewrite	^/extensions/all.shtml		http://xmpp.org/xmpp-protocols/xmpp-extensions/;
rewrite	^/extensions/editor.shtml	http://xmpp.org/about-xmpp/xsf/xsf-people/#extensions;
rewrite	^/extensions/index.php		http://xmpp.org/xmpp-protocols/xmpp-extensions/;
rewrite	^/extensions/index.shtml	http://xmpp.org/xmpp-protocols/xmpp-extensions/;
rewrite	^/extensions/ipr-policy.shtml	http://xmpp.org/about-xmpp/xsf/xsf-ipr-policy/;
rewrite	^/extensions/jep-\(.*\).html	http://xmpp.org/extensions/xep-\1.html;
rewrite	^/extensions/refs/jsf-xeps.tgz	http://xmpp.org/extensions/refs/xsf-xeps.tgz;
rewrite	^/extensions/refs/jsf-xeps.zip	http://xmpp.org/extensions/refs/xsf-xeps.zip;
rewrite	^/extensions/submit.shtml	http://xmpp.org/xmpp-protocols/xmpp-extensions/;
rewrite	^/history.html			http://xmpp.org/about/history.shtml;
rewrite	^/ietf-1999.html		http://xmpp.org/about/ietf-1999.shtml;
rewrite	^/ietf-chat.html		http://www.ietf.org/jabber/;
rewrite	^/ietf-logs			http://jabber.ietf.org/logs/;
rewrite	^/index.shtml			http://xmpp.org/;
rewrite	^/internet-drafts/$		http://xmpp.org/xmpp-protocols/internet-drafts/;
rewrite	^/interop/			http://wiki.xmpp.org/web/Interop;
rewrite	^/irtf-chat.html		http://www.ietf.org/jabber/;
rewrite	^/irtf-logs			http://jabber.ietf.org/logs/;
rewrite	^/im-services			http://xmpp.net/;
rewrite	^/jeps				http://xmpp.org/extensions/;
rewrite	^/jsf				http://xmpp.org/xsf/;
rewrite	^/members			http://xmpp.org/xsf/members/;
rewrite	^/protocol/$			http://xmpp.org/xmpp-protocols/protocol-namespaces/;
rewrite	^/protocols/$			http://xmpp.org/xmpp-protocols/protocol-namespaces/;
rewrite	^/protocols/([^:]+):([^:]+):([^:]+)$		http://xmpp.org/protocols/$1_$2_$3;
rewrite	^/registrar/$			http://xmpp.org/resources/registrar/;
rewrite	^/registrar/disco-nodes.html	http://xmpp.org/registrar/nodes.html;
rewrite	^/registrar/si.html		http://xmpp.org/registrar/si-profiles.html;
rewrite	^/registrar/index.php		http://xmpp.org/resources/registrar/;
rewrite	^/registrar/index.shtml		http://xmpp.org/resources/registrar/;
rewrite	^/resources/public-services/$	http://xmpp.net/;
rewrite	^/resources/public-services/registration/$		http://xmpp.net/;
rewrite	^/resources/public-services/verification/$		http://xmpp.net/;
rewrite	^/rfcs/$			http://xmpp.org/xmpp-protocols/rfcs/;
rewrite	^/rfcs/index.shtml		http://xmpp.org/xmpp-protocols/rfcs/;
rewrite	^/schemas/$			http://xmpp.org/resources/schemas/;
rewrite	^/schemas/index.shtml		http://xmpp.org/resources/schemas/;
rewrite	^/schemas/activity/activity.xsd		http://xmpp.org/schemas/activity.xsd;
rewrite	^/schemas/client.xsd		http://xmpp.org/schemas/jabber-client.xsd;
rewrite	^/schemas/server.xsd		http://xmpp.org/schemas/jabber-server.xsd;
rewrite	^/schemas/stanzas.xsd		http://xmpp.org/schemas/stanzaerror.xsd;
rewrite	^/schemas/xhtml-im/xhtml-im-model.xsd		http://xmpp.org/schemas/xhtml-im-model.xsd;
rewrite	^/services/$			http://xmpp.net/;
rewrite	^/services/index.shtml		http://xmpp.net/;
rewrite	^/services/register.shtml	http://xmpp.net/;
rewrite	^/services/verify.shtml		http://xmpp.net/;
rewrite	^/summary.html			http://xmpp.org/about/summary.shtml;
rewrite	^/software/$			http://xmpp.org/xmpp-software/;
rewrite	^/software/index.html		http://xmpp.org/xmpp-software/;
rewrite	^/software/index.shtml		http://xmpp.org/xmpp-software/;
rewrite	^/software/clients.html		http://xmpp.org/xmpp-software/clients/;
rewrite	^/software/clients.shtml	http://xmpp.org/xmpp-software/clients/;
rewrite	^/software/libraries.html	http://xmpp.org/xmpp-software/libraries/;
rewrite	^/software/libraries.shtml	http://xmpp.org/xmpp-software/libraries/;
rewrite	^/software/servers.html		http://xmpp.org/xmpp-software/servers/;
rewrite	^/software/servers.shtml	http://xmpp.org/xmpp-software/servers/;
rewrite	^/specs				http://xmpp.org/rfcs/;
rewrite	^/sponsors			http://xmpp.org/xsf/sponsors/;
rewrite	^/summit/$			http://xmpp.org/participate/the-xmpp-summit/;
rewrite	^/summit/index.shtml		http://xmpp.org/participate/the-xmpp-summit/;
rewrite	^/summit/summit1.shtml		http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-1/;
rewrite	^/summit/summit2.shtml		http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-2/;
rewrite	^/summit/summit3.shtml		http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-3/;
rewrite	^/summit/summit4.shtml		http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-4/;
rewrite	^/summit/summit5.shtml		http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-5/;
rewrite	^/summit/summit6.shtml		http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-6/;
rewrite	^/summit/summit7.shtml		http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-7/;
rewrite	^/summit/summit8.shtml		http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-8/;
rewrite	^/summit/summit9.shtml		http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-9/;
rewrite	^/trademark			http://xmpp.org/about-xmpp/xsf/jabber-trademark/;
rewrite	^/tech/bosh.shtml		http://xmpp.org//about-xmpp/technology-overview/bosh/;
rewrite	^/tech/core.shtml		http://xmpp.org//about-xmpp/technology-overview/core/;
rewrite	^/tech/index.shtml		http://xmpp.org//about-xmpp/technology-overview/;
rewrite	^/tech/$			http://xmpp.org//about-xmpp/technology-overview/;
rewrite	^/tech/jingle.shtml		http://xmpp.org//about-xmpp/technology-overview/jingle/;
rewrite	^/tech/muc.shtml		http://xmpp.org//about-xmpp/technology-overview/muc/;
rewrite	^/tech/overview.shtml		http://xmpp.org//about-xmpp/technology-overview/;
rewrite	^/tech/pubsub.shtml		http://xmpp.org//about-xmpp/technology-overview/pubsub/;
rewrite	^/web/Clients/			http://xmpp.org/xmpp-software/clients/;
rewrite	^/web/Quickstart		http://xmpp.org/xmpp-software/clients/;
rewrite	^/web/Servers			http://xmpp.org/xmpp-software/servers/;
rewrite	^/web/FAQ			http://xmpp.org/about/;
rewrite	^/wg-charter.html		http://xmpp.org/about/wg-charter.txt;
rewrite	^/xeps				http://xmpp.org/extensions/;
rewrite	^/xmppbis.html			http://xmpp.org/internet-drafts/;
rewrite	^/xsf/$				http://xmpp.org/about-xmpp/xsf/;
rewrite	^/xsf/index.shtml		http://xmpp.org/about-xmpp/xsf/;
rewrite	^/xsf/board			http://xmpp.org/about-xmpp/xsf/the-xsf-board-of-directors/;
rewrite	^/xsf/contact.shtml		http://xmpp.org/participate/contact-us/;
rewrite	^/xsf/council			http://xmpp.org/council/;
rewrite	^/xsf/director.shtml		http://xmpp.org/xsf/xsf-people/;
rewrite	^/xsf/docs/bylaws.shtml		http://xmpp.org/about-xmpp/xsf/xsf-bylaws/;
rewrite	^/xsf/docs/$			http://xmpp.org/about-xmpp/xsf/xsf-organizational-documents/;
rewrite	^/xsf/financialsummary.shtml	http://xmpp.org/about-xmpp/xsf/xsf-financial-summary/;
rewrite	^/xsf/mission.shtml		http://xmpp.org/about-xmpp/xsf/xsf-mission/;
rewrite	^/xsf/people.shtml		http://xmpp.org/xsf/xsf-people/;
rewrite	^/xsf/roadmap.shtml		http://xmpp.org/about-xmpp/xsf/xsf-roadmap/;
rewrite	^/xsf/secretary.shtml		http://xmpp.org/xsf/xsf-people/;
rewrite	^/xsf/sourcecontrol.shtml		http://xmpp.org/about-xmpp/xsf/xsf-source-control/;
rewrite	^/xsf/treasurer.shtml		http://xmpp.org/xsf/xsf-people/;
rewrite	^/xsf/privacy.shtml		http://www.jabber.org/service-policy/;
rewrite	^/xsf/voting.shtml		http://xmpp.org/about-xmpp/xsf/xsf-voting-procedure/;
rewrite	^/xsf/members/$			http://xmpp.org/about-xmpp/xsf/xsf-member-list/;
rewrite	^/xsf/members/index.shtml	http://xmpp.org/about-xmpp/xsf/xsf-member-list/;
rewrite	^/xsf/members/memberlist.shtml	http://xmpp.org/about-xmpp/xsf/xsf-member-list/;
rewrite	^/xsf/members/responsibilities.shtml	http://xmpp.org/participate/become-a-member/;
rewrite	^/xsf/people			http://xmpp.org/xsf/xsf-people/;
rewrite	^/xsf/proposals			http://xmpp.org/about-xmpp/xsf/xsf-proposals/;
rewrite	^/xsf/sponsors			http://xmpp.org/sponsor/;
rewrite	^/xsf/teams/$			http://xmpp.org/participate/become-a-member/#work;
rewrite	^/xsf/teams/index.shtml		http://xmpp.org/participate/become-a-member/#work;
rewrite	^/xsf/teams/communication	http://xmpp.org/participate/become-a-member/the-xsf-communication-team/;
rewrite	^/xsf/teams/infrastructure	http://xmpp.org/participate/become-a-member/the-xsf-infrastructure-team/;
rewrite	^/xsf/teams/techreview		http://xmpp.org/participate/become-a-member/the-xsf-technical-review-team/;
rewrite	^/xsf/XSF.ics			http://xmpp.org/calendar/xsf-all.ics;

**Comment by imaginator** [comment]
Thanks @Kev.

Some of these look pretty old. Do you have an idea of which ones are still being matched?

**Comment by guusdk** [comment]
If missing content was truly missed, we'd have noticed by now. I'm closing this old, inactive issue. Don't let that stop you from creating new issues when needed.
