### ISSUE TITLE
Explain "XMPP" and "XFS" on landing page 

### ISSUE THREAD

**Issue by penguineer** [xsf/xmpp.org#173]
When opening "xmpp.org" in the browser, the user is faced with two acronyms: XMPP and XFS.

While XMPP might be explainatory, as the user navigated the site with the URI "http://xmpp.org" and the slogan is very likely linked with the domain, the XFS (in "The XSF is generously sponsored by:") remains a mystery.

I tried to Google the term, but "XFS" turns up the Wikipedia page on the file system and xfs.org, which is the SGI page regarding the XFS file system.

I suggest that the term XFS directly links to the page About/The XFS (http://xmpp.org/about/xmpp-standards-foundation.html) for clarification.

For XMPP I found no such page, but I suppose that this acronym should be explained, too.

**Comment by penguineer** [comment]
Addendum: I just found "XMPP" in the footer, so there are two different pages:
* http://xmpp.org/about
* http://xmpp.org/about/technology-overview.html

Maybe those pages can be merged?
The menu item "Overview" could be named "XMPP Overview".

**Comment by ge0rg** [comment]
The PR provided does not address the last issue: content duplication between about and technology-overview. I think this came up already some time ago, but was not worked at.

My feeling is that the "about" page doesn't add much content besides of too-large headings, and the technology-overview page is better suited for the task.

**Comment by guusdk** [comment]
Progress stalled on this issue. Replacing/merging 'about' with 'overview' could be an improvement, but there does not seem to be any incentive to work on this. The remaining change does not warrant an everlasting unresolved issue, I think. I'm going to close this issue, but feel free to submit PRs to apply the change none-the-less.
