### ISSUE TITLE
Should 'projects' be merged with 'uses'?

### ISSUE THREAD

**Issue by guusdk** [xsf/xmpp.org#176]
[Software -> Projects](http://xmpp.org/software/projects.html) mostly describes very large third party products that use XMPP in some form. It is quite similar to the second half of the [Uses -> Social](http://xmpp.org/uses/social.html) and [Uses -> WebRTC](http://xmpp.org/uses/webrtc.html) pages.

Perhaps the (Software -> Projects) page content should be moved to various pages under "Uses"? That would make things more consistent.

**Comment by bear** [comment]
I would be +1 to that change and would merge it if something liked that appeared as a PR

**Comment by guusdk** [comment]
I took a stab at it. Most of the community-size numbers got lost. I moved the push notification projects to the 'XMPP social' usage. Not sure if that's the best place for it.

I did remove the old page, but perhaps some redirect-magic should be put in place to catch external links to the original URL?

**Comment by bear** [comment]
I'll merge the work after I get the redirect in place - thanks

**Comment by guusdk** [comment]
@bear I think that all that needs to be done is to add a redirect from the old, now unavailable [Software -> Projects](http://xmpp.org/software/projects.html) page.

**Comment by bear** [comment]
redirect is in place - closing issue
