### ISSUE TITLE
convert blog posts only to markdown

### ISSUE THREAD

**Issue by bear** [xsf/xmpp.org#19]
per issue #17 the following need to be converted:

    http://xmpp.org/2015/05/eyeball-networks/ 
    http://xmpp.org/2015/04/xsf-gsoc-students-2015/
    http://xmpp.org/2015/03/board-goals-for-2015/
    http://xmpp.org/2015/03/summit-17-the-presentations/
    http://xmpp.org/2015/03/an-introduction-to-xmppresearch-org/
    http://xmpp.org/2009/02/google-summer-of-code/
    http://xmpp.org/2015/03/xmpp-in-google-summer-of-code-2015/
    http://xmpp.org/2015/03/no-its-not-the-end-of-xmpp-for-google-talk/
    http://xmpp.org/2015/02/thank-you-xsf-sponsors/
    http://xmpp.org/2015/01/its-all-about-choices-and-control/
    http://xmpp.org/2015/01/xmpp-summit-17/
    http://xmpp.org/2014/05/upcoming-events/
    http://xmpp.org/2014/05/happy-encrypted-network/
    http://xmpp.org/2014/04/xmpp-on-the-global-internet-of-things-day/
    http://xmpp.org/2014/04/security-notice-uncontrolled-resource-consumption-with-highly-compressed-xmpp-stanzas/
    http://xmpp.org/2014/03/third-security-test-day/

**Comment by bear** [comment]
I have initial markdown files for all pages, drafts and blog posts from the wordpress site as of Sep 9th 2015.

If you give me some guidance as to what the target directory structure should be I can tweak the conversion script to generate it.

**Comment by imaginator** [comment]
@bear: `/content/posts/blog/`  is the place to be :)

**Comment by bear** [comment]
@imaginator cool - i'll take a look at the metadata in the example posts and ensure that the old posts have the same pattern tonight.

**Comment by imaginator** [comment]
@bear - any luck with this? Would be nice to see http://new.xmpp.org/posts/blog/index.html updated :)

**Comment by adambrault** [comment]
@bear do you have these markdown files so we can get them added to the blog? :)

**Comment by bear** [comment]
was kinda distracted this past couple of weeks -- I'll get this task done tonight or tomorrow

**Comment by bear** [comment]
everything but those items that were drafts has been imported

**Comment by adambrault** [comment]
@bear thanks!
