### ISSUE TITLE
Add apple-touch icons

### ISSUE THREAD

**Issue by guusdk** [xsf/xmpp.org#190]
Follow-up to #165 : There are a bunch of 404's in the server logs that relate to:
- /apple-touch-icon-precomposed.png
- /apple-touch-icon.png

There is a fair number of requests for those, so I'd be in favor for adding/restoring them.

**Comment by horazont** [comment]
Is this still an issue? The HTML metadata links to ``/icons/apple-icon-72x72.png`` and others, which appear to exist on the webserver.

**Comment by guusdk** [comment]
I have no access to the access logs, so I don't know how often the others are still referred to. At some point, we should re-do the 404-check effort, after which we can recreate issues like these if needed.
