### ISSUE TITLE
Favicon looks a bit flat

### ISSUE THREAD

**Issue by tfar** [xsf/xmpp.org#191]
Our old one was one with transparent background and a slight outline around the shape https://gitorious.org/xmpp/xmpp.git/?p=xmpp:xmpp.git;a=blob_plain;f=favicon.ico;hb=HEAD .

**Comment by Zash** [comment]
Transparent background is nice. That old one seems to be created in a more pixel art way instead of scaled down from the vector logo.

**Comment by guusdk** [comment]
So, we've got the old one, which I also like - but the new website has various resized version (all bigger than https://gitorious.org/xmpp/xmpp.git/?p=xmpp:xmpp.git;a=blob_plain;f=favicon.ico;hb=HEAD)

I don't think we can upscale that one properly, which leaves us with:

- try to track down the original author
- try to recreate the favicon ourselves
- only replace the smallest favicon with the prettier one.

**Comment by guusdk** [comment]
The 'prettier' favicon was a Pidgin one. We've been discussing using those again, but they appear to be GPL licensed. As we're not sure if that means that we can use them, we should err on the side of caution.

I'm closing this issue for now. If someone cares to provide better favicons, please re-open or create a new issue.
