### ISSUE TITLE
Figure out if we still need a schema directory

### ISSUE THREAD

**Issue by tfar** [xsf/xmpp.org#192]
The [old site](https://gitorious.org/xmpp/xmpp?p=xmpp:xmpp.git;a=tree;f=schemas;h=e802ba2d1788468494480733a5bb626bbf85205d;hb=HEAD) had a directory with schemas. Do we want to keep it? If so, where? In the pelican website, this repo? In a new repo?

**Comment by horazont** [comment]
Yes, it is needed to cross-reference schemas in XEPs. For example [XEP-0198](https://xmpp.org/extensions/xep-0198.html) references http://xmpp.org/schemas/stanzaerror.xsd. Simply grepping for http://xmpp.org/schemas in the XEPs will find a lot of other uses.

Where to keep it I don’t know. The current version on the website also needs updating.

**Comment by guusdk** [comment]
Those schemas are maintained here, right? https://github.com/xsf/schemas

@Kev - is this easily added to the automation magic that we now have?

**Comment by horazont** [comment]
We got a request about a missing on the editor list. We need a solution for this.

**Comment by guusdk** [comment]
https://xmpp.org/schemas/ seems to be already serving the schemas?

**Comment by horazont** [comment]
Huh. So two things happened: (1) archive-management.xsd is missing for some reason (probably because it hasn’t gone to draft yet?) and (2) I confused registries with schemas.

Possibly, everything is operating as it should?

**Comment by stpeter** [comment]
In the past we haven't added schemas to that directory until a specification moves beyond Experimental. It seems everything is working as designed. :-)

**Comment by wurstsalat3000** [comment]
@mwild1 can this issue be closed? https://xmpp.org/schemas/ exists

**Comment by Kev** [comment]
> @Kev do you have an additional comment on this topic?

I don't think I'm the right person to ask of this any more, sorry. Matt's now chief iteam person, and I no longer know how the site is generated.

**Comment by mwild1** [comment]
I think the issue was already answered in 2017:

> Yes, it is needed to cross-reference schemas in XEPs.

And we have it. So I'm not sure why this issue would need to remain open.
