### ISSUE TITLE
XML parser error: http://xmpp.org/extensions/xep-0xxx.xml

### ISSUE THREAD

**Issue by alexara** [xsf/xmpp.org#196]
URL in question: http://xmpp.org/extensions/xep-0300.xml
Counts for all other existing xep-0xxx.xml where x \in [0,9].

FF 46.0.1 64:

```
XML parse error: Not defined entity address: http://xmpp.org/extensions/xep-0312.xml
Row 11, column 3:  &LEGALNOTICE;
--^
```

Chromium 50.0.2661.102 Ubuntu 16.04 (64-bit) simply shows nothing.

**Comment by linkmauve** [comment]
Firefox doesn’t even try to access the file describing the entities, I’d say it’s a bug on their side.

But the website also lacks the two xep.xsl and xep.ent files in /extensions/, which can be found in https://github.com/xsf/xeps. Once you put them there Epiphany will display the XEP correctly (and I assume Chromium too).

**Comment by SamWhited** [comment]
We could probably serve the XML files with a mime type of `application/octet-stream` to force the browser to download the XML files instead of displaying annoying warnings, but I'm not sure that behavior is ideal either.

**Comment by Kev** [comment]
On 23 Jul 2016, at 16:37, Sam Whited <notifications@github.com> wrote:
> We could probably serve the XML files with a mime type of application/octet-stream to force the browser to download the XML files instead of displaying annoying warnings, but I'm not sure that behavior is ideal either.

Adding the two missing files seems sensible to me. I don’t think changing the mime type would be the Right Thing to do, though.

/K

**Comment by intosi** [comment]
Should be fixed now.  xep.{dtd,ent,xsl} are now served out.
