### ISSUE TITLE
Archived XEP versions are rendered incorrectly

### ISSUE THREAD

**Issue by ralphm** [xsf/xmpp.org#202]
Older versions of XEPs, in the so-called attic, don't render properly, because the referenced CSS file is `/xmpp.css`, which is missing. An example is http://www.xmpp.org/extensions/attic/xep-0048-1.0.html

**Comment by guusdk** [comment]
This probably is an easy fix: either the generated attic XEPs should get a reference to that file, which relatively exists "one level down" (as http://www.xmpp.org/extensions/xmpp.css), or the xmpp.css file could be copied to the attic. It does appear to be in the [xeps](https://github.com/xsf/xeps) repository, over which I weild no power.

**Comment by SamWhited** [comment]
We also have issues with XEPs in subdirectories of the build tree in the xeps repo not being able to find the CSS, and in the inbox, etc.

Is there a way to make HTML portable in general without including the CSS in the file itself?

**Comment by guusdk** [comment]
Always use this to reference to the css:

`<link rel="stylesheet" type="text/css" href="/extensions/xmpp.css"/>`

That should work for any file on that server, no matter where it lives (assuming that there's no 'base' element set).

**Comment by guusdk** [comment]
I've put in place a fix that resolves the issue. The fix, introduced in #259, should be temporary (as it duplicates the missing xmpp.css file).

Please remove that duplicate when a proper fix is put in place.

**Comment by guusdk** [comment]
Sadly, didn't have the desired effect. I'm assuming that the root of the content of the website does not get automatically redeployed (as it did appear to work in my local instance). I've reverted #259.

**Comment by SamWhited** [comment]
I also attempted to solve this, but don't know enough XSLT to make it work. Embedding the files in xep.xsl results in escaping issues in the JavaScript. I'm not really sure what else we could try; maybe copy/pasting the css/js files around (or symlinking them) is the best we can do.

**Comment by guusdk** [comment]
Let's have a HTTP redirect from /xmpp.css to /extensions/xmpp.css

In any case, we need help from someone with access to the server. @bear? @intosi?

**Comment by intosi** [comment]
Added redirects from /xmpp.css and /extensions/attic/xmpp.css to /extensions/xmpp.css
