### ISSUE TITLE
Various issues with the trademark pages

### ISSUE THREAD

**Issue by linkmauve** [xsf/xmpp.org#203]
These two pages, as linked from the main Jabber trademark page, don’t exist currently: https://xmpp.org/about/xsf/jabber-trademark/guidelines and https://xmpp.org/about/xsf/jabber-trademark/dispute-resolutions
The first one should be https://xmpp.org/about/xsf/jabber-trademark/usage-guidelines instead, I haven’t found the second one.

https://xmpp.org/about/xsf/jabber-trademark/pending-applications links to http://tracker.xmpp.org/browse/TRADEMARKS (which redirects to https://xmpp.org/), it should instead maybe list the open issues on github tagged with a trademark tag for example.

https://xmpp.org/about/xsf/jabber-trademark/who-needs-a-license says “described elsewhere on this web site”, this should be replaced with a link.

The various “please contact us” links point to https://xmpp.org/contact but it might be useful to add an id on the trademark paragraph to link directly to it.

The first link on https://xmpp.org/about/xsf/jabber-trademark/whats-required points to https://xmpp.org/about/xsf/jabber-trademark/trademark-license-agreement/ (with a final slash), which doesn’t exist, this one should redirect to the same URL without the final slash, or maybe just the link should be fixed.

**Comment by ge0rg** [comment]
Please reopen the issue, we are not done yet. I'm quoting the still-open things from the first comment:

> https://xmpp.org/about/xsf/jabber-trademark/pending-applications links to http://tracker.xmpp.org/browse/TRADEMARKS (which redirects to https://xmpp.org/), it should instead maybe list the open issues on github tagged with a trademark tag for example.

Indeed, we need to improve the process and document it.

> https://xmpp.org/about/xsf/jabber-trademark/who-needs-a-license says “described elsewhere on this web site”, this should be replaced with a link.

I'm planning to re-read all the different documents regarding trademarks and to make a single point of entry to them.

> The various “please contact us” links point to https://xmpp.org/contact but it might be useful to add an id on the trademark paragraph to link directly to it.
> 
> The first link on https://xmpp.org/about/xsf/jabber-trademark/whats-required points to https://xmpp.org/about/xsf/jabber-trademark/trademark-license-agreement/ (with a final slash), which doesn’t exist, this one should redirect to the same URL without the final slash, or maybe just the link should be fixed.

Still needs fixing.

**Comment by Echolon** [comment]
@ge0rg may you have time to review on this again?

**Comment by ge0rg** [comment]
The first link in the sidebar goes to https://xmpp.org/about/xsf/jabber-trademark.html instead of https://xmpp.org/about/xsf/jabber-trademark/

Still not fixed:
> https://xmpp.org/about/xsf/jabber-trademark/pending-applications links to http://tracker.xmpp.org/browse/TRADEMARKS (which redirects to https://xmpp.org/), it should instead maybe list the open issues on github tagged with a trademark tag for example.

I haven't had the time to read through everything, but the other links look consistent at least.

**Comment by mwild1** [comment]
Just checked with the new version of the website.

The page at https://xmpp.org/about/xsf/jabber-trademark/pending-applications/ links to tracker.xmpp.org which hasn't existed for years.

I propose we just remove the "pending applications" page. We don't track pending applications on Github, and I don't want to commit to tracking them via the website either.

@ralphm @stpeter do you see any reason we can't just remove this page? (e.g. a legal or contractual obligation to publish a list of pending applications)

**Comment by wurstsalat3000** [comment]
The link to tracker.xmpp.org has been removed in 7e826d46d8d8146f42c9256b67e3d4ef9073572d

**Comment by Echolon** [comment]
So this can be closed?

**Comment by Echolon** [comment]
I assume the links need to be replaced by a new reference, right?
