### ISSUE TITLE
XSF People page missing editor section

### ISSUE THREAD

**Issue by SamWhited** [xsf/xmpp.org#206]
The following link is included in `xep.ent` and is currently broken: `http://xmpp.org/about-xmpp/xsf/xsf-people/#editor`.

The page in question currently redirects to `http://xmpp.org/about/xsf/people#editor`, but there is no editor section on that page.

**Comment by SamWhited** [comment]
I've fixed the link to point to the new page in `xep.ent`, but there may be other links so it might be worth moving the page back to a section on the xsf-people page, or providing a link from that page at least.

**Comment by guusdk** [comment]
https://xmpp.org/about/xsf/people has a link to the editor team in the side bar. Does that suffice?

**Comment by SamWhited** [comment]
It would be nice if http://xmpp.org/about-xmpp/xsf/xsf-people/#editor worked just in case it's linked elsewhere, but it doesn't really matter to me.

**Comment by guusdk** [comment]
Agreed. It doesn't hurt to have a redirect from ``/about/xsf/people#editor`` to ``/about/xsf/editor-team.html``

Sadly, I can't create those. @intosi @bear?

**Comment by horazont** [comment]
@guusdk You can’t make server-side redirects from URLs with ``#`` in them—the part behind and including the ``#`` is only interpreted client side and never transmitted to the server.

**Comment by guusdk** [comment]
I learn something every day. Assuming that we don't want to do weird client-sided stuff, I think that's it for this issue?

**Comment by horazont** [comment]
Can we give the link to the editors team in the sidebar a ``name="editor"`` attribute? Then the UA will at least jump to that link.

**Comment by guusdk** [comment]
That's more confusing than helpful, I think - it'd marginally scroll the page, as the link is pretty high up. Feel free to add it, but I don't think it's worth the effort.
