### ISSUE TITLE
Kontalk in clients list?

### ISSUE THREAD

**Issue by Necklaces** [xsf/xmpp.org#208]
Hey, I am unsure, so let's discuss; this list https://xmpp.org/software/clients.html doesn't list "kontalk" https://kontalk.org/ which says it's based on XMPP. Add it or naw?

**Comment by guusdk** [comment]
Can Kontalk be used to reach another network than it's own?

**Comment by Necklaces** [comment]
@guusdk 
Not entirely sure what you're asking for here, do note taht I am not affiliated with Kontalk but;
1. I'm pretty sure one can set up a Kontalk server with a public IP to allow others to connect to it, effectively allowing on to use Kontalk to reach "another network" than it's own.
2. Kontalk [calls itself](https://github.com/kontalk/specs/wiki/XMPP) 100% XMPP compliant, meaning it is also compatible with all other XMPP clients (and other XMPP services?).

**Comment by guusdk** [comment]
It appears to me (but I'm not certain) that Kontalk is a 'closed' network: Kontalk clients are used to Kontalk servers. Would it be possible to use a Kontalk client to connect to any other, generic, XMPP server? I believe that this should be a deciding factor for the client to be added to the client list on the XSF page.

**Comment by daniele-athome** [comment]
@guusdk well, you can point the client to another server, but registration and authentication require some extension (all the server-side source code is open and available), so you can't successfully connect to **any** XMPP server, not without having those extensions installed. But for the rest Kontalk is a plain XMPP client. I don't know if it can qualify for the clients list.
DISCLAIMER: I'm the project leader.

**Comment by guusdk** [comment]
Thanks for pitching in, @daniele-athome. I'm assuming that those extensions are proprietary? Even though it's all XMPP under water, it would make your client not practically usable for users that want to pick out a client to connect to a regular XMPP domain. I believe that this is the intended purpose for that list.

We do have other pages, that lists projects that make use of XMPP (this one, for example: http://xmpp.org/uses/instant-messaging). Perhaps that's a more suitable place to mention Kontalk?

**Comment by daniele-athome** [comment]
> I'm assuming that those extensions are proprietary?

Yes, for the moment. It's actually a custom data form used with XEP-0077 for doing phone number verification (2-step registration). There is something being discussed about multiple step registration IIRC, but until standardization...

> Perhaps that's a more suitable place to mention Kontalk?

I guess! What do I have to do to be included there? (Note: xmpp.org is currently down, all 3 DNS servers failed to respond)

**Comment by daniele-athome** [comment]
I saw this: https://github.com/xsf/xmpp.org/blob/master/content/pages/uses/instant-messaging.md

Can I edit it and make a PR?

**Comment by guusdk** [comment]
Absolutely :)

**Comment by daniele-athome** [comment]
I've created PR #219.
