### ISSUE TITLE
“Commercial” license in list of software?

### ISSUE THREAD

**Issue by Wuzzy2** [xsf/xmpp.org#209]
On https://xmpp.org/software/servers.html and https://xmpp.org/software/libraries.html some software is listed to be under a “commercial” license.
This is either vague or just plain wrong, but in any case it is misleading.

Please do not use “commercial” as a synonym for “proprietary” as those two things are distinct categories. Free software (as in freedom) can be given away without cost, or for a fee. The same is true for prorietary software.

The license field should be either changed to simply “No license (copyright)” (since this is usually the default if no license is explicitly used) or “Custom proprietary license” (usually EULAs with many restrictions). Whatever is correct for the particular software. But “commercial” is just too vague and misleading.

**Comment by intosi** [comment]
I am inclined to disagree, and close this ticket as a wontfix.  The meaning of Commercial seems clear enough to most if not all readers.  This sounds to me like pedantry.

**Comment by Wuzzy2** [comment]
It's not about “the meaning of ‘commercial’”.

My problem is that “commercial” seems to be used as a synoym for “proprietary” which is clearly wrong as those two things are distinct and should not be conflated.

It just advances the false premise that “proprietary = commercial” which is NOT true at all.

Example: If the server Citadel (GPLv3) would be only made available for a fee, what should be written into the column? “Commercial” or “GPLv3”? See the problem here? The program would be BOTH commercial (since it is sold) and under the GPLv3. The paradox can be solved by writing “GPLv3” for this software and by dismissing “Commercial” as a “license” and just call it “Proprietary” / “No license (copyright)” / etc. instead.

The Free Software Foundation says this:
https://www.gnu.org/philosophy/words-to-avoid.html.en#Commercial

**Comment by bear** [comment]
All discussions of licensing is pedantic just by the nature of the topic.

The larger point is that your asking us to change the language by swapping one English-lawyer-speak word with another which will bring out more discussions about licensing.

I would suggest that we just remove the column completely - the information is almost never updated for changes and anyone looking will be visiting the respective site and discover it in that manner.

**Comment by stpeter** [comment]
+1 to what @bear says.

**Comment by Wuzzy2** [comment]
What about simplifying it to “free software y/n”?

**Comment by SamWhited** [comment]
> What about simplifying it to “free software y/n”?

Same weird legal waffle issues. The Stallmanites will complain that MIT or BSD licensed things aren't "free software" they're "open source" and you're a terrible person if you use them.

Agree this column should just be removed.

**Comment by Wuzzy2** [comment]
> Same weird legal issues. The Stallmanites will complain that MIT or BSD licensed things aren't "free software" they're "open source" and you're a terrible person if you use them.

Not true at all. MIT and BSD are also free software (they easily fit all of the criteria) and FSF-approved. Even rms himself has nothing against the licenses. Copyleft is NOT a requirement for being free software. Also, free software and open source are actually very similar in their official definition (look it up). While the FSF claims that copyleft is strategically “better”, they do NOT dismiss non-copyleft licenses solely for not having copyleft.

It should be quite easy to determine whether a software is free software or not. If sources are provided, and the license is FSF-approved or OSI-approved or even both, then it is safe to assume that the software is free software.

**Comment by SamWhited** [comment]
Whatever; the point is that there are licenses that some people consider free, and the FSF (or whomever, it was just an example) don't. Someone else with a different opinion of what free software means will just complain again later. I don't have any problem with the columns as they stand now, personally, but it seems worth just getting rid of them to me to have one less thing that we have to keep up with.

**Comment by Wuzzy2** [comment]
From my experience, I can tell you that disputes on whether a software qualfies as “free software” (or “open source”, whatever) are actually rare and even if they happen, they are settled quickly. Probably this is because the official definition of “free software” is pretty clear and can be easily checked by anyone. (The same applies to the term “open source”, of course.):

- No license: Proprietary
- No source code: Proprietary
- Obviously restrictive license (e.g. copying is prohibited): Proprietary
- Has public source code (and other essential files) + FSF and/or OSI-approved license: Free software
- Has public source code (and other essential files) and an obscure license: Needs to be checked manually, but I predict this situation will be rather rare. When in doubt, just leave the field empty

If you need help in determining whether a software in the list is “free software” or not, I could help.

Any potential confusion about the term “free software” (or “open source”) itself can be easily resolved by referring to the official definition.

Also, just because a license is not approved by FSF or OSI does not mean it is not a free software license. Approval is more like a official confirmation. But luckily, obscure licenses are rare.

Whatever, I wish I have never opened this issue, now the homepage is at risk of becoming worse than before because it may contain less information in the future.
:-(

**Comment by guusdk** [comment]
Having less data is an improvement over having data that's likely incorrect/outdated. I've created PR that removes the license columns on both pages.

**Comment by bear** [comment]
Thanks @guusdk !

**Comment by Wuzzy2** [comment]
Sigh. :-(

**Comment by bear** [comment]
@Wuzzy2 this doesn't preclude adding back two columns that contain the information you outlined above. 

But I can say that the method you outlined above would require quite a bit of overhead for anyone who needs to maintain the list and that is why I opted for the method of removing the information for the moment
