### ISSUE TITLE
Comparison data about clients

### ISSUE THREAD

**Issue by wilsonmar** [xsf/xmpp.org#212]
I think it would be useful if additional information is presented about each client on page
https://github.com/xsf/xmpp.org/blob/master/content/pages/software/clients.md
like what is at
https://www.wikiwand.com/en/Comparison_of_instant_messaging_clients

That page does not filter out only XMPP.

But for now how about adding a link to that Wikipedia page?

**Comment by guusdk** [comment]
I'm not sure if the goal of our page should be to provide all available data on XMPP implementations around the world. We recently [had a discussion on a similar matter](https://github.com/xsf/xmpp.org/issues/209), that resulted in us removing data, instead of adding more.

**Comment by horazont** [comment]
I think we should at least defer it until the renewal deadline is over. Maintaining that information is hard. If we let the client implementations do it, we may want to review that the information is correct, which is also hard.

**Comment by ge0rg** [comment]
It would be great to have a comprehensive list of clients and their features, but this is a very tedious task, and the information will deprecate fast.

I think we should add the following items to the display:
* short description of the client (we should enforce a sensible upper limit to this)
* which compliance suite it corresponds to

These two should be easy to maintain as part of the new [annual update process](https://xmpp.org/2017/03/new-xmpp-software-listing-rules), and people can obtain additional info by following the link.

A full list / comparison of client features can be maintained on the wiki, or even on wikipedia.

**Comment by guusdk** [comment]
The renewal deadline is over, and 'the purge' has occurred.

Are we still interested in maintaining additional data?

**Comment by horazont** [comment]
Lets give clients a month or two extra time, we’ve seen that some only noticed The Purge when it happened. We can then outline the requirements for the next renewal, e.g. by requiring clients renewed after 2018-01-01 to have the additional information.

**Comment by ge0rg** [comment]
If we had specified the requirements before initiating The Purge, we would have complete data by now. Let's not delay further, but just add fields to the display.

I still think that the two proposed above (short description, compliance suite) are a great trade-off.

**Comment by 1000i100** [comment]
For me, software licences are as important as plateform compatibility.
I'm really sad it has been removed in #210.

**Comment by Echolon** [comment]
The doap file will also improve in terms of "tedious work"

**Comment by wurstsalat3000** [comment]
Additional data is now displayed using DOAP files (if available). An example can be seen here: https://xmpp.org/software/clients/conversations/
