### ISSUE TITLE
Information on the source control page is out of date

### ISSUE THREAD

**Issue by SamWhited** [xsf/xmpp.org#218]
http://xmpp.org/about/xsf/source-control

Mentions that you check out from GitHub, then starts talking about a GitHub mirror (which is the same URL). Also, I don't think we have a repo on perseus that authors are allowed to check things into anymore.

**Comment by guusdk** [comment]
Updated the text. By-the-by, are you aware that changes like these are pretty trivial to do? Given your "mad XEP editor skillz0rz", I'm surprised that you created an issue, instead of a PR here :)

**Comment by SamWhited** [comment]
@guusdk I avoid touching the website at all costs. I don't want to use Python or Pelican (or make untested PRs).

**Comment by guusdk** [comment]
I'm doing Python nor Pelican - it's all Markdown - pretty easy. 

Also, I've recently added a Vagrant image that will automatically provision a virtual machine that you can easily use to generate and run the website locally. As easy as:

```
$ vagrant up
$ vagrant ssh
$ cd /vagrant
$ make devserver
```

**Comment by SamWhited** [comment]
Fixed by Guus; thanks!
