### ISSUE TITLE
Re-add as blog posts

### ISSUE THREAD

**Issue by adambrault** [xsf/xmpp.org#22]
- [ ] convert originals to markdown files
- [ ] re-add as blog posts with proper metadata

---

- [ ] http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-1/
- [ ] http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-2/
- [ ] http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-3/
- [ ] http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-4/
- [ ] http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-5/
- [ ] http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-6/
- [ ] http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-7/
- [ ] http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-8/
- [ ] http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-9/
- [ ] http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-10/
- [ ] http://xmpp.org/participate/the-xmpp-summit/xmpp-summit-11/

**Comment by bear** [comment]
per Issue #19 I have the markdown files for these - if you show me what the metadata is needed I can adjust them as part of the conversion

**Comment by adambrault** [comment]
this was included in @bear's work on #19
