### ISSUE TITLE
Broken links to /xmpp-protocols/protocol-namespaces/

### ISSUE THREAD

**Issue by SamWhited** [xsf/xmpp.org#241]
`https://xmpp.org/protocol/` currently redirects to `https://xmpp.org/xmpp-protocols/protocol-namespaces/` which also doesn't exist.

**Comment by guusdk** [comment]
Is this intended instead? https://xmpp.org/registrar/namespaces.html

If so, we might someone that wields the power to modify those redirects. @intosi? @bear?

**Comment by intosi** [comment]
I think https://xmpp.org/extensions/ would be most appropriate, considering what this contained way back when (see https://web-beta.archive.org/web/20060925030129/http://www.jabber.org/protocol/ )

**Comment by guusdk** [comment]
@intosi / @Kev could you please apply the change to the existing redirect then?

**Comment by guusdk** [comment]
https://xmpp.org/protocol/ now redirects to https://xmpp.org/extensions/
