### ISSUE TITLE
Add a redirection from HTTP to HTTPS and enable HSTS

### ISSUE THREAD

**Issue by linkmauve** [xsf/xmpp.org#243]
Since the HTTPS version of the website is robust now, it should only be a matter of removing the `listen 80` and `listen [::]:80` in nginx and adding this catchall server section:
```
server {
    listen 80;
    listen [::]:80;
    server_name _; # anything invalid is fine here, it will act as a wildcard
    location / {
        return 301 https://$host$request_uri;
    }
}
```

As for HSTS, it would fix part of #152, each server section should get a new line containing:
```
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
```

**Comment by intosi** [comment]
This was on my todo, thanks for the reminder :)  I think it's safe to implement this sooner rather than later.

**Comment by Kev** [comment]
I'd suggest the 301 first, and then HSTS after a couple of weeks if noone shouts.

**Comment by Zash** [comment]
One could also go with HSTS first, capturing anyone foolishly typing in https or following a https link from elsewhere.

**Comment by intosi** [comment]
The 301 part has been done.  The HSTS header is already there, but commented out.  Will enable that in roughly two weeks time.

**Comment by intosi** [comment]
Enabled HSTS as well.
