### ISSUE TITLE
Missing favicon on wiki.xmpp.org

### ISSUE THREAD

**Issue by linkmauve** [xsf/xmpp.org#251]
`/favicon.ico` 404s, despite the `<link rel="shortcut icon"/>`.

**Comment by Neustradamus** [comment]
Here: https://web.archive.org/web/20100522005148/http://xmpp.org/favicon.ico
@bear has noted that it was missing.

In the same time, I have requested to add this image on the planet more 5 years ago: https://planet.jabber.org/images/xmpp.png, you can use it ;)

**Comment by guusdk** [comment]
@intosi Is this something that you have the power to fix?

**Comment by intosi** [comment]
Added
