### ISSUE TITLE
Add /resources section, add this content

### ISSUE THREAD

**Issue by adamavenir** [xsf/xmpp.org#26]
- [ ] http://xmpp.org/resources/
- [ ] http://xmpp.org/resources/security-notices/
- [ ] http://xmpp.org/resources/certificates/
- [ ] http://xmpp.org/resources/registrar/
- [ ] http://xmpp.org/resources/schemas/
- [ ] http://xmpp.org/resources/books/

**Comment by adambrault** [comment]
Which of this content do we need for launch, how much of it is accurate, and where should it go?

**Comment by Echolon** [comment]
@wurstsalat3000 what do you think on this?

I recently thought about collecting literature and papers on XMPP.

**Comment by wurstsalat3000** [comment]
At the moment, we have:

* https://xmpp.org/community/security-notices/
* Certificates is not relevant anymore I guess
* https://xmpp.org/registrar/
* https://xmpp.org/schemas/
* Books section is missing

@Echolon I think a "Books" / "Literature" section would be most fitting for papers and other published work. I don't know why there is no "Books" page anymore.

**Comment by wurstsalat3000** [comment]
Books section has been added in d888715dcb865a44892d4f725553ce0565819e6d

I've added redirect for the rest (apart from /registrar and /schemas).
