### ISSUE TITLE
Update Extensions page to 2017

### ISSUE THREAD

**Issue by Neustradamus** [xsf/xmpp.org#261]
Please update Extensions page "https://xmpp.org/extensions" to 2017:
https://xmpp.org/extensions/xep-0387.html

**Comment by SamWhited** [comment]
This page is updated automatically, and appears to have the latest XEPs for me. Maybe you have a cached copy and refreshing will fix it?

**Comment by guusdk** [comment]
I'm not sure what the update frequency is (perhaps there was a gap between issue creation and the update that made things right)? In any case, it's working for me too. Closing this issue.
