### ISSUE TITLE
Mention Emeritus XSF members on website

### ISSUE THREAD

**Issue by guusdk** [xsf/xmpp.org#275]
The emeritus members of the XSF deserve to be on the website.

**Comment by guusdk** [comment]
As @agnauck pointed out, the emeritus members are listed on the bottom of https://xmpp.org/about/xsf/members

Should we, perhaps, dedicate a bit more of virtual space to them? Define why they're considered emeritus members, for instance?

**Comment by guusdk** [comment]
I'm afraid that I know none of these, and need your help. Please leave a paragraph of text for each of these members here, and I'd be happy to give that a nice place on the website somewhere.

**Comment by stpeter** [comment]
Those were the core contributors of the original jabber.org team.

**Comment by stpeter** [comment]
Also, I don't think we need to have special mention of these folks - just listing them as emeritus members seems fine to me.

**Comment by tfar** [comment]
I don't see no harm in mentioning that they were the core contributors of the original jabber implementation. I don't feel strong either way.

**Comment by stpeter** [comment]
I'd call this wontfix (the site is good enough as-is).
