### ISSUE TITLE
Update or remove Event page

### ISSUE THREAD

**Issue by guusdk** [xsf/xmpp.org#276]
https://xmpp.org/community/events.html contains out of date information. We should either update it (and keep it updated), or remove that page.

**Comment by Nyco** [comment]
We got: https://wiki.xmpp.org/web/Meetups

Which should we maintain?

**Comment by guusdk** [comment]
As far as I'm concerned, the intended target for the wiki is XSF members, while the intended target for the website is anyone interested in XMPP. That's why I'd prefer to move the meetups page from the wiki to the website.
