### ISSUE TITLE
Find problems in the web server access logs.

### ISSUE THREAD

**Issue by guusdk** [xsf/xmpp.org#303]
I'd like to be able to find and fix some 'real-world' problems, based from errors logged in the web server access logs.

Could someone please provide the access logs for the last few days? I'd like to parse them for any status code >= 400, group and count requests that triggered them, and see if there's something there worth fixing.

**Comment by horazont** [comment]
Interesting would also be 3xx logs with a referrer which originates from xmpp.org, because it indicates that we should update links somewhere.

**Comment by guusdk** [comment]
I've been grepping over the access log for xmpp.org (which contains data for roughly the last six days.

Finding all 404's with a referrer that is our own site:
``cat xmpp.org.access.log | grep " 404 " | awk -F'"' '{print "REF",$4,"URL",$2}' | grep "REF https://xmpp.org" | sort | uniq -c | sort``

The top few findings:

    10 REF https://xmpp.org/extensions/attic/xep-0313-0.5.html URL GET /extensions/attic/prettify.css HTTP/1.1
    10 REF https://xmpp.org/extensions/attic/xep-0313-0.5.html URL GET /extensions/attic/prettify.js HTTP/1.1
    17 REF https://xmpp.org/about/technology-overview.html URL GET /rfcs/rfc7622.html HTTP/1.1
    22 REF https://xmpp.org/about/xmpp-standards-foundation URL GET /about/process-one.net HTTP/1.1

Finding 301's that originate from xmpp.org gives interesting results:

      10 REF https://xmpp.org/ URL GET /community HTTP/1.1
      10 REF https://xmpp.org/about/ URL GET /uses HTTP/1.1
      10 REF https://xmpp.org/about/faq.html URL GET /software HTTP/1.1
      11 REF https://xmpp.org/about/technology-overview.html URL GET /getting-started HTTP/1.1
      11 REF https://xmpp.org/blog.html URL GET /getting-started HTTP/1.1
      11 REF https://xmpp.org/extensions/index.html URL GET /theme/images/xmpp-logo.png HTTP/1.1
      11 REF https://xmpp.org/internet-drafts/ URL GET /xmpp-protocols/internet-drafts/ HTTP/1.1
      12 REF https://xmpp.org/software/servers.html URL GET /software HTTP/1.1
      13 REF https://xmpp.org/getting-started/ URL GET /theme/images/xmpp-logo.png HTTP/1.1
      13 REF https://xmpp.org/uses/internet-of-things.html URL GET /theme/images/xmpp-logo.png HTTP/1.1
      13 REF https://xmpp.org/uses/webrtc.html URL GET /getting-started HTTP/1.1
      14 REF https://xmpp.org/blog.html URL GET /2017/08/easy-xmpp-the-challenges HTTP/1.1
      15 REF https://xmpp.org/ URL GET /extensions HTTP/1.1
      15 REF https://xmpp.org/software/clients.html URL GET /about HTTP/1.1
      15 REF https://xmpp.org/uses/instant-messaging.html URL GET /theme/images/xmpp-logo.png HTTP/1.1
      16 REF https://xmpp.org/about/ URL GET /getting-started HTTP/1.1
      16 REF https://xmpp.org/software/servers.html URL GET /about HTTP/1.1
      18 REF https://xmpp.org/software/ URL GET /getting-started HTTP/1.1
      20 REF https://xmpp.org/community/chat.html URL GET /getting-started HTTP/1.1
      20 REF https://xmpp.org/software/libraries.html URL GET /getting-started HTTP/1.1
      22 REF https://xmpp.org/about/xmpp-standards-foundation URL GET /about/xsf/jabber-trademark HTTP/1.1
      22 REF https://xmpp.org/about/xmpp-standards-foundation URL GET /community HTTP/1.1
      22 REF https://xmpp.org/about/xmpp-standards-foundation URL GET /extensions HTTP/1.1
      22 REF https://xmpp.org/about/xmpp-standards-foundation URL GET /getting-started HTTP/1.1
      22 REF https://xmpp.org/about/xmpp-standards-foundation URL GET /software HTTP/1.1
      22 REF https://xmpp.org/about/xmpp-standards-foundation URL GET /uses HTTP/1.1
      22 REF https://xmpp.org/registrar/disco-categories.html URL GET /xmpp.css HTTP/1.1
      23 REF https://xmpp.org/ URL GET /uses HTTP/1.1
      23 REF https://xmpp.org/about/xmpp-standards-foundation URL GET /about HTTP/1.1
      23 REF https://xmpp.org/getting-started URL GET /getting-started/ HTTP/1.1
      23 REF https://xmpp.org/registrar/mucstatus.html URL GET /xmpp.css HTTP/1.1
      31 REF https://xmpp.org/registrar/namespaces.html URL GET /xmpp.css HTTP/1.1
      31 REF https://xmpp.org/theme/images/xmpp-logo.png URL GET /theme/images/xmpp-logo.png HTTP/1.1
      38 REF https://xmpp.org/2015/03/no-its-not-the-end-of-xmpp-for-google-talk/ URL GET /theme/images/xmpp-logo.png HTTP/1.1
      42 REF https://xmpp.org/software/ URL GET /theme/images/xmpp-logo.png HTTP/1.1
      45 REF https://xmpp.org/extensions/ URL GET /theme/images/xmpp-logo.png HTTP/1.1
      57 REF https://xmpp.org/ URL GET /about HTTP/1.1
      58 REF https://xmpp.org/uses/webrtc.html URL GET /theme/images/xmpp-logo.png HTTP/1.1
      61 REF https://xmpp.org/2017/08/easy-xmpp-the-challenges URL GET /2017/08/easy-xmpp-the-challenges HTTP/1.1
      61 REF https://xmpp.org/uses/instant-messaging.html URL GET /getting-started HTTP/1.1
      62 REF https://xmpp.org/2017/08/easy-xmpp-the-challenges URL GET /2017/08/easy-xmpp-the-challenges/ HTTP/1.1
      64 REF https://xmpp.org/software/servers.html URL GET /getting-started HTTP/1.1
      81 REF https://xmpp.org/software/clients.html URL GET /getting-started HTTP/1.1
     154 REF https://xmpp.org/about/ URL GET /theme/images/xmpp-logo.png HTTP/1.1
     206 REF https://xmpp.org/about/technology-overview.html URL GET /theme/images/xmpp-logo.png HTTP/1.1
     220 REF https://xmpp.org/software/libraries.html URL GET /theme/images/xmpp-logo.png HTTP/1.1
     324 REF https://xmpp.org/ URL GET /getting-started HTTP/1.1
     582 REF https://xmpp.org/ URL GET /software HTTP/1.1
     695 REF https://xmpp.org/software/servers.html URL GET /theme/images/xmpp-logo.png HTTP/1.1
    1454 REF https://xmpp.org/software/clients.html URL GET /theme/images/xmpp-logo.png HTTP/1.1
    1793 REF https://xmpp.org/ URL GET /theme/images/xmpp-logo.png HTTP/1.1

302:

     10 REF https://xmpp.org/about/xmpp-standards-foundation.html URL GET /extensions.html HTTP/1.1
     10 REF https://xmpp.org/uses/ URL GET /uses/webrtc HTTP/1.1
     14 REF https://xmpp.org/about/technology-overview.html URL GET /software/libraries HTTP/1.1
     19 REF https://xmpp.org/software/servers.html URL GET /software/servers HTTP/1.1
     22 REF https://xmpp.org/about/xmpp-standards-foundation URL GET /about/../extensions.html HTTP/1.1
     22 REF https://xmpp.org/about/xmpp-standards-foundation URL GET /community/membership HTTP/1.1
     22 REF https://xmpp.org/about/xmpp-standards-foundation URL GET /contact HTTP/1.1
     36 REF https://xmpp.org/about/discuss.shtml URL GET /about/discuss.shtml HTTP/1.0
     36 REF https://xmpp.org/about/technology-overview.html URL GET /software/servers HTTP/1.1
     37 REF https://xmpp.org/about/technology-overview.html URL GET /software/clients HTTP/1.1
     37 REF https://xmpp.org/getting-started/ URL GET /software/clients HTTP/1.1
     63 REF https://xmpp.org/ URL GET /extensions.html HTTP/1.1
    138 REF https://xmpp.org/software/ URL GET /software/libraries HTTP/1.1
    273 REF https://xmpp.org/software/ URL GET /software/clients HTTP/1.1
    351 REF https://xmpp.org/software/ URL GET /software/servers HTTP/1.1

**Comment by wurstsalat3000** [comment]
@guusdk can this issue be closed?
