### ISSUE TITLE
Dead Link: IPR Policy

### ISSUE THREAD

**Issue by stpeter** [xsf/xmpp.org#325]
The IPR policy has moved from https://xmpp.org/about/xsf/ipr-policy  to https://xmpp.org/about/xsf/ipr-policy.html - we need to update our pointers (e.g., from https://xmpp.org/about/standards-process.html and NOTE from all XEPs so the XSLT needs fixing too).

**Comment by guusdk** [comment]
Although we should update the pointers, there might be references outside of our control. I'd like to have a forward from the old to new URL, to complement the changes to our own content. Configuring the forwards is out of my control though (although I wish it wasn't - this pops up regularly - is there anything we can improve there, @Kev ?)

**Comment by Kev** [comment]
There is - we can set up the rules inside the docker container that deploys the website (which is under version control, although I'd prefer ours), instead of the host.

**Comment by guusdk** [comment]
You're referring to @dwd's repo? I thought everyone agreed to move that to our repo? Can't we (someone with admin powers here) migrate that here?

**Comment by guusdk** [comment]
I'm actually finding several variants of the 'old' address. Not sure if they ever worked, but perhaps we should have forwarding rules for all of these:
- /about/xsf/ipr-policy
- /about/xsf/xsf-ipr-policy/
- /about/ipr-policy
- /about-xmpp/xsf/xsf-ipr-policy/
- /extensions/ipr-policy.shtml (which already redirects to a 404 on https://xmpp.org/about/xsf/ipr-policy)

These are all intended to go to /about/xsf/ipr-policy.html - right?

Also, the references to footnotes in https://xmpp.org/about/standards-process.html link to http://xmpp.org/extensions/ipr-policy.shtml#note1 (and #note2) which redirects to https://xmpp.org/about/xsf/ipr-policy#note1 and 2 (which both 404's). The reference in that document needs to be updated (I can do that), but the redirect needs to be modified too. I'll create the required anchors ( /about/xsf/ipr-policy.html#note1 and /about/xsf/ipr-policy.html#note2 )

**Comment by guusdk** [comment]
The PR above addresses the content on the public webpage - but not in the extensions.

I am starting to wonder if there's a larger problem here. The timing of this issue, as well as #321 is curious. Did these links work before the server was resurrected?

**Comment by guusdk** [comment]
The missing .html issue will likely be fixed with https://github.com/dwd/xsf-web-docker/pull/1 although the issue of having multiple different URLs will likely still need some work. I'll redo my commit later tonight.

**Comment by guusdk** [comment]
That fix was now applied, which indeed resolves a lot of issues on the website. I still need to redo my PR to fix the remaining few broken links.

**Comment by guusdk** [comment]
After the fix was applied, only a couple of links still failed. I'll update the content on our website, but we should also have redirects for the following:

* /about/xsf/xsf-ipr-policy -> /about/xsf/ipr-policy/
* /about/ipr-policy -> /about/xsf/ipr-policy/

Redirects are already in place for these links (but I'll update our content to replace them by the canonical URL nonetheless:

* /extensions/ipr-policy.shtml
* /about-xmpp/xsf/xsf-ipr-policy (was already fixed by @ge0rg's #342 )

**Comment by guusdk** [comment]
With https://github.com/xsf/xmpp.org/pull/347 - I believe I've addressed this issue fully (please re-open this issue if I missed something). As https://github.com/dwd/xsf-web-docker/pull/1 restored the functionality of the links that @stpeter reported, changes to XEP XSLT should no longer be required.
