### ISSUE TITLE
Meeting minutes

### ISSUE THREAD

**Issue by adambrault** [xsf/xmpp.org#33]
http://xmpp.org/about-xmpp/xsf/meeting-minutes/

These need to be ported to markdown pages in ``content/pages/about/xsf/records/meeting-minutes``

**Comment by bear** [comment]
The meeting minutes pages are now in markdown from the work i'm doing for Issue #19

**Comment by bear** [comment]
meeting minutes are now imported

**Comment by adambrault** [comment]
thanks, @bear!
