### ISSUE TITLE
Some chat history links still broken

### ISSUE THREAD

**Issue by SamWhited** [xsf/xmpp.org#330]
The links to http://logs.xmpp.org/operators/ and http://logs.xmpp.org/xsf/ from https://xmpp.org/community/chat.html are still broken.

As far as I know, those links should actually include the full room JID (like the jdev link above, that is working), but it still doesn't work if I change it to that, so there may be two issues here.

/cc @tfar

**Comment by guusdk** [comment]
Hattip to @intosi

**Comment by guusdk** [comment]
Jabber.org links are still broken, but we've got another issue for that: https://github.com/xsf/xmpp.org/issues/73
