### ISSUE TITLE
https://xmpp.net/directory.php 404's

### ISSUE THREAD

**Issue by mischief** [xsf/xmpp.org#349]
see title

**Comment by guusdk** [comment]
The entire observatory needs to be restored, not just that one address.

**Comment by mischief** [comment]
my apologies - i only clicked the directory link from https://xmpp.org/getting-started/ . please edit or close the issue if you see fit :-)

**Comment by mischief** [comment]
it looks like the directory has been fixed.

**Comment by guusdk** [comment]
Indeed, it was restored over the weekend. I forgot about this ticket and neglected to update it, apologies. Thanks for taking care of it.
