### ISSUE TITLE
Broken link to xmpp-protocols

### ISSUE THREAD

**Issue by SamWhited** [xsf/xmpp.org#377]
There is a link to https://xmpp.org/xmpp-protocols/ from https://developers.google.com/cloud-print/docs/rawxmpp which appears to be broken.

> The XMPP Standards Foundation lists more information on the protocol and on XML schemas here.

I'm not sure what it used to be.

**Comment by horazont** [comment]
All my browser history knows is that ``/xmpp-protocols/xmpp-extensions/`` used to be the XEP index. The Internet Archive also has no idea what was at ``/xmpp-protocols/``. I wonder whether we’ll be fine if we simply redirect to ``/extensions/`` (that gives an entry point to both the RFCs and the XEPs, which from the text seems reasonable).

**Comment by wurstsalat3000** [comment]
Where are redirects managed for xmpp.org ?

I checked `/deploy/xsf.conf`, but these redirect do not work/seem not to be in use currently.
