### ISSUE TITLE
Compliance suite link at top of /extensions is wrong

### ISSUE THREAD

**Issue by SamWhited** [xsf/xmpp.org#398]
Currently there is a link to the retracted 2016 suites at the top of the /extensions page. This link should probably be removed if we can't automate it since it will likely never be kept up to date.

**Comment by mwild1** [comment]
For the record, I fixed it manually in #436 (unaware this issue was filed). I agree automating it would be nice, however I also like that it's there and would rather not remove it.

**Comment by SamWhited** [comment]
I was about to file this issue again when I saw the PR to fix it forgetting that I had already filed this; I agree it's nice to have a link there, but if it's never going to be kept up to date (and I don't see why it ever would be) I also think it's way worse if we have the 2018 suites listed 4 years from now when they are no longer relavant.

I feel the same way about the compatibility suites in general, if we don't have a specific person keeping them up and can't find a process to put them into effect at the beginning of the year, it just looks worse for us than not having them at all.
