### ISSUE TITLE
Logos in client list

### ISSUE THREAD

**Issue by ge0rg** [xsf/xmpp.org#405]
It would be great to support additional fields in the client / server / (library?) list:

 * logo
 * download (for mobile clients this would be the respective platform store)
 * maybe also a description (which should have an appropriate length limit)?

I'd like to do the start:
 * Bruno: https://op-co.de/tmp/bruno-64.png
    * https://play.google.com/store/apps/details?id=org.yaxim.bruno
 * Conversations:  https://raw.githubusercontent.com/siacs/Conversations/master/art/ic_launcher.svg
    * https://play.google.com/store/apps/details?id=eu.siacs.conversations
 * yaxim: https://op-co.de/tmp/yak-front-grass.svg
    * https://play.google.com/store/apps/details?id=org.yaxim.androidclient

**Comment by jcbrand** [comment]
Converse.js: 
- logo: https://github.com/jcbrand/converse.js/blob/master/logo/conversejs128.png
- download: https://www.npmjs.com/package/converse.js

**Comment by Neustradamus** [comment]
- Psi: https://psi-im.org/ : https://github.com/psi-im/psi/blob/master/iconsets/system/default/logo_128.png
- Psi+: https://psi-plus.com/ : https://github.com/psi-plus/main/blob/master/iconsets/system/default/psiplus/logo_128.png
- Gajim: https://gajim.org/ : https://dev.gajim.org/gajim/gajim/blob/master/gajim/data/icons/hicolor/scalable/apps/org.gajim.Gajim.svg

**Comment by Dwisnewski** [comment]
Please add Tigase's clients & Servers:
Logo: https://tigase.tech/attachments/download/5645/tiger2sm.png
(If you need larger, pelase contact me, daniel-at-tigase.org)

Tigase: XMPP Server: 

- Nightly builds here: http://build.xmpp-test.net/nightlies/dists/latest/tigase-server-dist-max.zip
- Stable builds here: https://tigase.tech/projects/tigase-server/files
With latest stable download link here: https://tigase.tech/attachments/download/6054/tigase-server-7.1.3-b4482-dist-max.zip

Clients
Tigase Messenger for Android
https://play.google.com/store/apps/details?id=org.tigase.messenger.phone.pro&hl=en

Tigase Messenger for Ios
https://itunes.apple.com/us/app/tigase-messenger/id1153516838?ls=1&mt=8

**Comment by horazont** [comment]
Okay, I volunteered to get this done. Please try to provide rastered logos with 64x64 size or SVG. I’d like to avoid having to downscale rastered images myself. PNG format is preferred unless there’s a good reason not to.

**Comment by Echolon** [comment]
https://linkmauve.fr/software/clients.html

@linkmauve what it missing for a PR?

**Comment by Neustradamus** [comment]
@Echolon: Psi and Psi+ are missing...
