### ISSUE TITLE
XMPP Protocol Namespaces not complete

### ISSUE THREAD

**Issue by Neustradamus** [xsf/xmpp.org#413]
The namespace list is not complete:
- https://xmpp.org/registrar/namespaces.html
-- Last Updated: 2015-08-11

**Comment by Echolon** [comment]
@Neustradamus may you create a PR?

**Comment by wurstsalat3000** [comment]
This issue should be moved to https://github.com/xsf/registrar

**Comment by wurstsalat3000** [comment]
@SamWhited could you move this issue to https://github.com/xsf/registrar please? I don't have sufficient rights.

**Comment by SamWhited** [comment]
This issue doesn't mention why it's incomplete or what's missing, so it's not actually useful. Let's just close it instead (but I also have no rights on this issue tracker to move it).
