### ISSUE TITLE
RFCs are missing and maybe not updated for actual

### ISSUE THREAD

**Issue by Neustradamus** [xsf/xmpp.org#414]
The RFCs list is not complete and maybe not updated for actual (last 2019-06-21):
- https://xmpp.org/rfcs/

Status problems:
- RFC 3920
- RFC 3921
- RFC 3922
- RFC 3923 (no change)
- RFC 4622
- RFC 4854 (no change)
- RFC 5122
- RFC 6120
- RFC 6121 (no change)
- RFC 6122

New to old not on the website:
- RFC 8600
- RFC 8284
- RFC 8266
- RFC 8048
- RFC 7712
- RFC 7702
- RFC 7700
- RFC 7622
- RFC 7590
- RFC 7573
- RFC 7572
- RFC 7395
- RFC 7340
- RFC 7259
- RFC 7248
- RFC 7247
- RFC 7165
- RFC 7081
- RFC 5437
- RFC 4979

**Comment by wurstsalat3000** [comment]
Wouldn't it be nicer to have an overview page at xmpp.org/rfcs, which would list and describe relevant RFCs, and link to datatracker.ietf.org instead? This would surely minimize maintenance effort.
