### ISSUE TITLE
The new XMPP logo with XMPP text is missing

### ISSUE THREAD

**Issue by Neustradamus** [xsf/xmpp.org#415]
Some months ago, there was a little change on the logo.

The new is:
- https://xmpp.org/theme/images/xmpp-logo.svg

But between the old and the new, the XMPP has disappeared.

In addition, can you create a new SVG with the XMPP text?
xmpp-logo-with-text.svg for example

**Comment by Neustradamus** [comment]
On commons.wikipedia.org: https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

**Comment by wurstsalat3000** [comment]
Fixed in a84359c
