### ISSUE TITLE
Missing redirections

### ISSUE THREAD

**Issue by Neustradamus** [xsf/xmpp.org#419]
Year after year, there are missing redirections.

404 Not Found

- https://xmpp.org/about-xmpp/faq/
- https://xmpp.org/xmpp-protocols/xmpp-extensions/submitting-a-xep/
- https://xmpp.org/xmpp-protocols/
- https://xmpp.org/xmpp-protocols/xmpp-core/
- https://xmpp.org/participate/
- https://xmpp.org/participate/become-a-member/editor-team/
- https://xmpp.org/about-xmpp/xsf/meeting-minutes/
- https://xmpp.org/internet-drafts/attic/
- https://xmpp.org/participate/the-xmpp-summit/xmpp-summit-1/
- https://xmpp.org/participate/the-xmpp-summit/xmpp-summit-2/
- https://xmpp.org/participate/the-xmpp-summit/xmpp-summit-3/
- https://xmpp.org/participate/the-xmpp-summit/xmpp-summit-4/
- https://xmpp.org/participate/the-xmpp-summit/xmpp-summit-5/
- https://xmpp.org/participate/the-xmpp-summit/xmpp-summit-6/
- https://xmpp.org/participate/the-xmpp-summit/xmpp-summit-7/
- https://xmpp.org/participate/the-xmpp-summit/xmpp-summit-8/
- https://xmpp.org/participate/the-xmpp-summit/xmpp-summit-9/
- https://xmpp.org/participate/the-xmpp-summit/xmpp-summit-10/
- https://xmpp.org/participate/the-xmpp-summit/xmpp-summit-11/
- https://xmpp.org/resources/
- https://xmpp.org/resources/security-notices/
- https://xmpp.org/resources/certificates/
- https://xmpp.org/resources/registrar/
- https://xmpp.org/resources/schemas/
- https://xmpp.org/resources/books/
- https://xmpp.org/about/bof-minutes.txt
- https://xmpp.org/about/wg-charter.txt
- https://xmpp.org/about/ipr-notice.txt
...

Easy to list 404 errors from logs.

**Comment by lovetox** [comment]
https://xmpp.org/about/xsf/xsf-source-control

https://xmpp.org/extensions/xep-template.xml

**Comment by Nyco** [comment]
Please submit a PR.

**Comment by wurstsalat3000** [comment]
There seems to be no replacement for:

* https://xmpp.org/about-xmpp/faq/
* https://xmpp.org/resources/
* https://xmpp.org/resources/certificates/
* https://xmpp.org/resources/books/
* https://xmpp.org/about/bof-minutes.txt
* https://xmpp.org/about/wg-charter.txt
* https://xmpp.org/about/ipr-notice.txt

Redirects should happen in respective repos for:

* https://xmpp.org/resources/registrar/
* https://xmpp.org/resources/schemas/
* https://xmpp.org/internet-drafts/attic/
* https://xmpp.org/extensions/xep-template.xml (not sure why not available online; xeps repo has it)

**Comment by Neustradamus** [comment]
@wurstsalat3000: Can you solve the original bad newsletter link?
- https://github.com/xsf/xmpp.org/issues/532
- https://github.com/xsf/xmpp.org/issues/638

Thanks a lot in advance.
