### ISSUE TITLE
XMPP Extensions Editor announcements

### ISSUE THREAD

**Issue by Neustradamus** [xsf/xmpp.org#420]
A long time ago, announcements have been done by XMPP Extensions Editor with editor at xmpp.org.

It is possible to have this process again?
Better for rules...

Example: https://mail.jabber.org/pipermail/standards/2010-January/023039.html

**Comment by SamWhited** [comment]
No, not until we fix our infrastructure, automation, and tooling.

**Comment by Neustradamus** [comment]
Not invalid, it can be changed ^^
