### ISSUE TITLE
Old proposals are not redirected

### ISSUE THREAD

**Issue by Neustradamus** [xsf/xmpp.org#421]
There are always old proposals in the inbox, normally old proposals are redirected to its XEP (like previously).
Can you look for redirection?

https://xmpp.org/extensions/inbox/account-management.html
-> https://xmpp.org/extensions/xep-0376.html

https://xmpp.org/extensions/inbox/bidi.html
-> https://xmpp.org/extensions/xep-0288.html

https://xmpp.org/extensions/inbox/bookmarks2.html
-> https://xmpp.org/extensions/xep-0402.html

https://xmpp.org/extensions/inbox/cap.html
-> https://xmpp.org/extensions/xep-0395.html

https://xmpp.org/extensions/inbox/carbons.html
-> https://xmpp.org/extensions/xep-0280.html

https://xmpp.org/extensions/inbox/client-key.html
-> https://xmpp.org/extensions/xep-0399.html

https://xmpp.org/extensions/inbox/client-state-notification.html
-> https://xmpp.org/extensions/xep-0352.html

https://xmpp.org/extensions/inbox/cmr.html
-> https://xmpp.org/extensions/xep-0354.html

https://xmpp.org/extensions/inbox/colors.html
-> https://xmpp.org/extensions/xep-0392.html

https://xmpp.org/extensions/inbox/decloak.html
-> https://xmpp.org/extensions/xep-0276.html

https://xmpp.org/extensions/inbox/distributedmuc.html
-> https://xmpp.org/extensions/xep-0281.html

https://xmpp.org/extensions/inbox/dsig-design.html
-> https://xmpp.org/extensions/xep-0274.html

https://xmpp.org/extensions/inbox/dsig.html
-> https://xmpp.org/extensions/xep-0285.html

https://xmpp.org/extensions/inbox/fmuc.html
-> https://xmpp.org/extensions/xep-0289.html

https://xmpp.org/extensions/inbox/forwarding-delivery.html
-> https://xmpp.org/extensions/xep-0297.html

https://xmpp.org/extensions/inbox/incident-reporting.html
-> https://xmpp.org/extensions/inbox/incident-reporting.html

https://xmpp.org/extensions/inbox/isr-sasl2.html + https://xmpp.org/extensions/inbox/isr.html
-> https://xmpp.org/extensions/xep-0397.html

https://xmpp.org/extensions/inbox/jet-omemo.html
-> https://xmpp.org/extensions/xep-0396.html

https://xmpp.org/extensions/inbox/jet.html
-> https://xmpp.org/extensions/xep-0391.html

https://xmpp.org/extensions/inbox/jingle-ibb.html
-> https://xmpp.org/extensions/xep-0261.html

https://xmpp.org/extensions/inbox/jingle-nodes.html
-> https://xmpp.org/extensions/xep-0278.html

https://xmpp.org/extensions/inbox/jingle-rtp-mti.html + https://xmpp.org/extensions/inbox/jingle-rtp-codecs.html
-> https://xmpp.org/extensions/xep-0266.html

https://xmpp.org/extensions/inbox/jingle-s5b.html
-> https://xmpp.org/extensions/xep-0260.html

https://xmpp.org/extensions/inbox/jingle-zrtp.html
-> https://xmpp.org/extensions/xep-0262.html

https://xmpp.org/extensions/inbox/mix.html
-> https://xmpp.org/extensions/xep-0369.html

https://xmpp.org/extensions/inbox/mobile.html
-> https://xmpp.org/extensions/xep-0286.html

https://xmpp.org/extensions/inbox/moved.html
-> https://xmpp.org/extensions/xep-0283.html

https://xmpp.org/extensions/inbox/muji.html
-> https://xmpp.org/extensions/xep-0272.html

https://xmpp.org/extensions/inbox/outofband.html
-> https://xmpp.org/extensions/xep-0265.html

https://xmpp.org/extensions/inbox/pep-vcard-conversion.html
-> https://xmpp.org/extensions/xep-0398.html

https://xmpp.org/extensions/inbox/problem-reporting.html
-> https://xmpp.org/extensions/xep-0268.html

https://xmpp.org/extensions/inbox/pubsub-since.html
-> https://xmpp.org/extensions/xep-0312.html

https://xmpp.org/extensions/inbox/reputation.html
-> https://xmpp.org/extensions/xep-0275.html

https://xmpp.org/extensions/inbox/rsf.html
-> https://xmpp.org/extensions/xep-0351.html

https://xmpp.org/extensions/inbox/sasl2.html
-> https://xmpp.org/extensions/xep-0388.html

https://xmpp.org/extensions/inbox/sic.html
-> https://xmpp.org/extensions/xep-0279.html

https://xmpp.org/extensions/inbox/sift.html
-> https://xmpp.org/extensions/xep-0273.html

https://xmpp.org/extensions/inbox/spim.html
-> https://xmpp.org/extensions/xep-0287.html

https://xmpp.org/extensions/inbox/sxe.html
-> https://xmpp.org/extensions/xep-0284.html

https://xmpp.org/extensions/inbox/thumbs.html
-> https://xmpp.org/extensions/xep-0264.html

https://xmpp.org/extensions/inbox/user-invite.html
-> https://xmpp.org/extensions/xep-0401.html

https://xmpp.org/extensions/inbox/muc-selfping.html
-> https://xmpp.org/extensions/xep-0410.html

https://xmpp.org/extensions/inbox/bookmarks-conversion.html
-> https://xmpp.org/extensions/xep-0411.html

https://xmpp.org/extensions/inbox/cs-2019.html
-> https://xmpp.org/extensions/xep-0412.html

https://xmpp.org/extensions/inbox/hash-recommendations.html
-> https://xmpp.org/extensions/xep-0414.html

https://xmpp.org/extensions/inbox/eax-car.html
-> https://xmpp.org/extensions/xep-0416.html

**Comment by Neustradamus** [comment]
Any news?

I have updated the ticket.

**Comment by Nyco** [comment]
Please propose a PR for review.
