### ISSUE TITLE
Registrar section is not updated

### ISSUE THREAD

**Issue by Neustradamus** [xsf/xmpp.org#422]
There are missing files:
- https://xmpp.org/registrar/

**Comment by wurstsalat3000** [comment]
There is already an open issue for this in xsf/registrar

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/xsf/registrar/issues/31

**Comment by Neustradamus** [comment]
Dear @wurstsalat3000, can you reopen this ticket?

It is not up-to-date, you can see here: https://xmpp.org/registrar/

Last Updated: 2011-02-22

And @SamWhited has informed me that it is not a duplicate with https://github.com/xsf/registrar/issues/31.

**Comment by SamWhited** [comment]
I already told you that I'd talk to iteam about it. Please stop spamming everyone with notifications.

**Comment by Neustradamus** [comment]
@SamWhited: Yes but the ticket has been not solved, it is needed to keep open before correction, solution.

It is a tracking system.
