### ISSUE TITLE
Incorporate technology overview pages

### ISSUE THREAD

**Issue by ralphm** [xsf/xmpp.org#43]
http://xmpp.org/about-xmpp/technology-overview/

**Comment by guusdk** [comment]
I'm not sure what the status of this issue is. What needs to be done to be able to resolve and close this?

**Comment by ralphm** [comment]
Well, I suppose that URL now points to something again. The original pages were just more detailed. I'm not sure if that is desirable, though. See http://web.archive.org/web/20150313010246/http://xmpp.org/about-xmpp/technology-overview and https://github.com/xsf/site-archived/tree/master/content/pages. E.g. `pubsub.md`.

**Comment by guusdk** [comment]
OK, thanks. In that case, I'm closing this for now. We will reopen or recreate the issue when someone has specific improvements in mind.
