### ISSUE TITLE
/uses/realtime-web write content

### ISSUE THREAD

**Issue by imaginator** [xsf/xmpp.org#47]
We have XMPP uses for IOT, webrtc, im, social. But we're missing a section on realtime-web. I think @lloydwatkin and @legastero would be best placed to write two paragraphs on this.

**Comment by guusdk** [comment]
Are we still interested in having this? If so, is anyone willing to contribute?

**Comment by guusdk** [comment]
Apparently, there has not been any interest in actually providing content. I'm closing this issue for now.
