### ISSUE TITLE
How contact iteam for resolve problems linked to XSF: XMPP.net + XMPP.org

### ISSUE THREAD

**Issue by Neustradamus** [xsf/xmpp.org#483]
How it is possible to contact iteam for resolve problems?

https://xmpp.org/about/xsf/infrastructure-team : People on github + Jonathan Siegle
@guusdk @agnauck @tfar @intosi @stpeter @mwild1 @Kev

In the same time, I speak here about XMPP.org + XMPP.net because there are some configurations in common.

For the "independent" jabber.org service, you can see all (comments too) on the first ticket here: https://github.com/stpeter/jabberdotorg/issues/1 and other here: https://github.com/stpeter/jabberdotorg/issues.

**Comment by Nyco** [comment]
To contact iTeam, maybe a MUC, or direct chat. The best is to submit a PR here.
