### ISSUE TITLE
Xmpp.Org should include a attribution link to OpenDomain

### ISSUE THREAD

**Issue by opendomain** [xsf/xmpp.org#497]
I donated the domain Xmpp.Org to the Jabber Software Foundation.  In return, they agreed to link to OpenDomain.Org 

Please see:
https://web.archive.org/web/20070504093558/https://xmpp.org/xsf/press/2005-12-30.shtml

OpenDomain is a non profit project the supports Open Source.  The link request is to raise awareness of the project - we do not have advertising.  The link request is the same as all open source that requires all forks to include a copy of the license file.

**Comment by guusdk** [comment]
Thanks for bringing this to our attention. It would seem that such an agreement was forgotten about over time, rotation of people, and website designs. If that caused us to break a promise, then I apologize. As one of the current board members of the XSF, I'll make sure that we address this, @opendomain

**Comment by stpeter** [comment]
@guusdk Thanks! I know that some other domains have not fulfilled their promise (I don't see a link to OpenDomain.org from WordPress.com, for instance!), but I'd prefer if we keep to our word.

@opendomain Hi Ric, nice to hear from you again. :-)

**Comment by horazont** [comment]
@stpeter Thanks for chiming in on this.

@opendomain Do you have any artwork we could/should potentially use on the website? If there was any, it appears to have been lost in time. It would be good to have that ready when we figure out how to re-add the attribution!

**Comment by stpeter** [comment]
In the past we had a bit of text in the page footer acknowledging OpenDomain's help in obtaining xmpp.org. @opendomain can you share your preferred text?

**Comment by opendomain** [comment]
Our trademark is "Open Source for Domains" - because that is literally what we are.  Other OpenDomains include FosDem, OsCon, Schema.Org (Google), Drupal, Ecmascript, WebPlatfrom (W3C).  I have run this project close to 20 years. It is not for profit and has never sold a domain - this is my effort to give back to Open Source.

**Comment by stpeter** [comment]
@opendomain Yes, Ric, I recall our conversations on this topic, and I worked with you on both drupal.com and wordpress.com as well as the XMPP domains. I went to those sites and didn't see attribution of OpenDomain either. I'm just trying to figure out what text you'd like us to include. :-)

**Comment by opendomain** [comment]
St Peter
THIS is the problem with open source!  I have given domains worth millions to great projects but most do not follow the terms they agreed too.  All I ask is a link to promote the project.
I do not dictate the actual text used, but if you are looking for a suggestion we would prefer "Xmpp.Org domain donated for Free by OpenDomain"

**Comment by opendomain** [comment]
Any update?

**Comment by horazont** [comment]
@opendomain Sorry for the delay. I made a concrete proposal an #513, please see the attached screenshots there if the attribution is to your liking.
