### ISSUE TITLE
Pelican compatibility

### ISSUE THREAD

**Issue by guusdk** [xsf/xmpp.org#506]
The current website depends on Pelican version 3.3. When a newer version is used, the menu is not generated properly.

The website should work with up-to-date versions of Pelican.

**Comment by guusdk** [comment]
The Vagrant and docker configuration that ships as part of this repository pins Pelican at version 3.3. This provides an easy way to generate a fully functional website locally, but introduces the need to run a virtual container setup.

**Comment by SeveFP** [comment]
Example of the top bar with newer Pelican versions:
![https://i.imgur.com/5A262Il.png](https://i.imgur.com/5A262Il.png)

**Comment by Echolon** [comment]
Hello guys,

if this is still an issue, what do you recommend to do/ investigate?

**Comment by jcbrand** [comment]
Yes, this is still an issue and someone will have to spend the time to fix the site to work with newer versions of Pelican.

**Comment by wurstsalat3000** [comment]
I think I found the issue. The top_menu.html template is iterating "PAGES" instead of [lower-case "pages"](https://docs.getpelican.com/en/3.6.3/themes.html#common-variables). Changing to lowercase brought the menu back for me (using Pelican 4.2). Same for 'footer.html' and 'page.html' for footer and sidebar menus.

**Comment by jcbrand** [comment]
Please make a PR @wurstsalat3000 :)

**Comment by Echolon** [comment]
Hi @wurstsalat3000,

can you elaborate what the next step must be currently?

**Comment by wurstsalat3000** [comment]
@Echolon This PR only works with recent versions of Pelican. This means the Pelican version used for xmpp.org has to be updated (and with it, several other components, which might break stuff). So I see why there is some hesitation ;)
Sadly, this PR won’t work with both the currently used version of Pelican *and* newer versions, despite the documentation claiming Pelidan to be able to (Pelican’t). This makes it also difficult to test.
