### ISSUE TITLE
Newsletter link problem from 2019 (31 january)

### ISSUE THREAD

**Issue by Neustradamus** [xsf/xmpp.org#532]
Recall about the problem of link:
-> https://xmpp.org/2019/01/the-xmpp-newsletter-31-january-2018/

One month already.

**Comment by Neustradamus** [comment]
-> https://github.com/Nitron/pelican-alias

**Comment by Neustradamus** [comment]
Any news 8 months after?

**Comment by jcbrand** [comment]
@Neustradamus: Nodody seems to care enough about this to do anything about it, including you.

**Comment by Neustradamus** [comment]
I have informed you about: https://github.com/Nitron/pelican-alias...

**Comment by jcbrand** [comment]
I don't think it's worth installing a plugin just for this issue. I've already said multiple times (in other channels as well, not just this one) that this needs to be done in the webserver.

**Comment by Neustradamus** [comment]
@Nyco: Time to reopen this ticket, I will not create a new?
