### ISSUE TITLE
jackbeer protocol

### ISSUE THREAD

**Issue by idnovic** [xsf/xmpp.org#540]
This idea originated in the group chat at disroot.org.

By coincidence a user wrote jaqbber instead of jabber.
An other user read jackbeer.
A quick survey concluded that the jackbeer protocol would increase usage of jabber/xmpp.

For marketing purposes I suggest the acceptance of the jackbeer protocol as official naming for jabber.

Gratis marketing suggestions go as follows:
XMPP, our chat runs on beer.
Jackbeer, quantum beer encryption.
Beersharing with your friends. Try xmpp today.

Thank you!
Have a nice week :P

**Comment by guusdk** [comment]
🤣

Thank you for your suggestion and thorough market survey.

I have a sneaky suspicion that a fair amount of (jack)beer was involved
while performing said survey.

May I suggest formalizing this suggestion in a XEP, to be published on the
first day of next month, perhaps?

Op di 5 mrt. 2019 23:54 schreef Ivo Damjanovic <notifications@github.com>:

**Comment by jcbrand** [comment]
I prefer Jackbeer to Zimpy

**Comment by idnovic** [comment]
I will review and finalize it gladly.
I found the xmpp extensionspage.
What is the right place to create a XEP?


I was asked why jackbeer would increase the usage of xmpp:

whatsapp = whats my chat app,
xmpp does not make any sense to the user.
Jabber is a better name than xmpp in my opinion.
Jabber could be a dog or something, so Jabber is relatable.
You can not spell xmpp without spelling the letters one for one.
Jackbeer is funny, beer drinking is social (can be).

User needs something rememberable:
"hey catch my later at xmpp" nope wont ever happen,
"hey catch my at jackbeer" right, we should hang out, maybe drink a beer and grill.

Jackbeer might even increase social gatherings in RL.

**Comment by idnovic** [comment]
soo my further research concluded that jackbeer might be problematic without partnership.

https://www.jackbeer.fr/

So I will leave it as a joke. No further actions from my side.

Thank you.
