### ISSUE TITLE
 Adding an unbiased server list in page "getting started"

### ISSUE THREAD

**Issue by E-404** [xsf/xmpp.org#555]
Exclusion of biased directories from the "get started" page. XMPP should remain an independent community that does not lobby for the interests of individuals!
The directory list.Jabber.at is a personal directory, adding and deleting is determined by the admin jabber.at. If the site is like the admin jabber.at he adds it if he doesn’t like it.

We have created a directory in which does not divide the servers into bad and good, for biased reasons https://github.com/xsf/xmpp.org/pull/545

**Comment by horazont** [comment]
Stop spamming this tracker (and by extension, our inboxes). You already have a PR open.

**Comment by E-404** [comment]
We discovered a problem because it is a problem. We want not to bring this revision, we want xmpp.org to stop promoting the servers of the old participants!

**Comment by E-404** [comment]
When we are told that "_

> you did not achieve prestige on the streets and therefore cannot be included in the list of recommended servers

_" it sounds like nonsense!
