### ISSUE TITLE
Incomplete text on WebRTC page

### ISSUE THREAD

**Issue by willsheward** [xsf/xmpp.org#556]
Third paragraph on the WebRTC page (https://xmpp.org/uses/webrtc.html) stops unexpectedly:

"XMPP is particularly a great fit with WebRTC in settings where there is a desire to pair WebRTC audio/video calls with text chat, but the advantages of XMPP"

**Comment by Nyco** [comment]
Seems good to me:
![Capture d’écran 2019-11-14 à 17 09 17](https://user-images.githubusercontent.com/25348/68874478-8bcc3880-0701-11ea-904b-a9e8e0966c67.png)
