### ISSUE TITLE
Updated RFCs

### ISSUE THREAD

**Issue by stpeter** [xsf/xmpp.org#56]
At the least, we need to change RFC 6122 to RFC 7622.

Also adding RFC 7395 would be good.

**Comment by imaginator** [comment]
@stpeter which page are you referring to?

**Comment by linkmauve** [comment]
@imaginator http://xmpp.org/xmpp-protocols/rfcs/ which still contains a reference to RFC 6122 for XMPP ADDR instead of RFC 7622.

**Comment by stpeter** [comment]
Fixed by adding RFC links to the history page and the extensions page.
