### ISSUE TITLE
Alphabetic ordering in software listing

### ISSUE THREAD

**Issue by guusdk** [xsf/xmpp.org#566]
See #565: The existing code orders "Pàdé" behind "Pidgin". That aught to be reversed.

**Comment by Nyco** [comment]
Web page: https://xmpp.org/software/clients.html
Git page: https://github.com/xsf/xmpp.org/blob/master/content/pages/software/clients.md

How do we update the content? It is not in the markdown file...

**Comment by guusdk** [comment]
> How do we update the content? It is not in the markdown file...

See https://github.com/xsf/xmpp.org/blob/master/data/README.rst

**Comment by Nyco** [comment]
Thx @guusdk !

PR #637 should fix this issue, please review.

**Comment by Echolon** [comment]
As the fix has been merged I will close this!
Thanks!
