### ISSUE TITLE
Software comparsion tables for supported XEPs

### ISSUE THREAD

**Issue by Mikaela** [xsf/xmpp.org#585]
IRCv3 has nice comparsion tables that name the clients/servers/libraries and what IRCv3 extensions they support. I think the idea would port over well to XMPP as XEPs work similarly to IRCv3 extensions, but as there are so many of them, I guess just the compliance suites that users are going to see would be enough to be listed.

* https://ircv3.net/software/clients
* https://ircv3.net/software/servers
* https://ircv3.net/software/libraries

IRCv3.net is using Jekyll and the source is at https://github.com/ircv3/ircv3.github.io .

**Comment by ge0rg** [comment]
I suggest using the Compliance Suites for that, or maybe at least having an aggregate "Compliance Level" column for implementations, because the individual XEPs are very many and very noisy for normal users.

**Comment by wurstsalat3000** [comment]
https://xmpp.org/software/ can now be used to filter by Compliance level and by individual XEPs. I'll close this issue in favor of #1185
