### ISSUE TITLE
Google's XMPP Interface URL return 404

### ISSUE THREAD

**Issue by AJLoveChina** [xsf/xmpp.org#586]
![image](https://user-images.githubusercontent.com/11222746/61097689-d35e6180-a48e-11e9-9855-fa05d7a4876b.png)

The link (https://developers.google.com/cloud-messaging/server) to XMPP interface return 404.

**Comment by Nyco** [comment]
Web page: https://xmpp.org/uses/social.html
Repo page: https://github.com/xsf/xmpp.org/blob/master/content/pages/uses/social.md

Internet archive, wayback machine: https://web.archive.org/web/20170306032337/https://developers.google.com/cloud-messaging/server (March 2017)
