### ISSUE TITLE
ChatSecure not showing up on the list of XMPP clients

### ISSUE THREAD

**Issue by whalehub** [xsf/xmpp.org#587]
The iOS-exclusive XMPP client "ChatSecure" is not showing up on the [list of XMPP clients](https://xmpp.org/software/clients.html) even though it's listed in the [clients.json](https://github.com/xsf/xmpp.org/blob/master/data/clients.json) file.

![vivaldi_2019-07-16_20-48-09](https://user-images.githubusercontent.com/44198148/61321058-0b590200-a80b-11e9-99d1-9273a7a65ad8.png)

**Comment by guusdk** [comment]
For this list to be useful, it should contain up-to-date information about up-to-date software. To achieve this, the XSF Board has decided that all implementations have to reapply once per year, to ensure that they are still actively maintained and that the listed info is accurate.

Would you mind performing the renewal. That should be as easy as updating the `last_renewed` timestamp. More detailed instructions can be found in the [readme](https://github.com/xsf/xmpp.org/blob/master/data/README.rst).

**Comment by whalehub** [comment]
@guusdk I spent the past two hours going through all clients and servers to bring their information up-to-date. Please have a look at #588, which fixes this issue.
