### ISSUE TITLE
Create a super-simple intro page for end users

### ISSUE THREAD

**Issue by stpeter** [xsf/xmpp.org#60]

**Comment by theSouL** [comment]
I would like to suggest using a diagram like one I did in the past: [http://i.imgur.com/HN6p6gn.png](http://i.imgur.com/HN6p6gn.png)

I'm not saying using the one I posted, it's just a drawing of the idea. I think showing federation using logos (from well known applications, e.g gmail, facebook, wordpress, etc) and talking about the email or telephone analogies is a good way to help people understand XMPP in the easiest way.

**Comment by jaykay12** [comment]
Is the issue still unresolved???

**Comment by bear** [comment]
appears to be still open

**Comment by locutis-of-borg-1999** [comment]
Yeah, it seems that none of the blunderbuss bunch on the project's MUCs really care.  Neither does Cisco, Google, Facebook, Kik, etc.  I once did.  The abuse from trolls on the MUCs disabused me of such zealotry.  

But, there's real hope with the Matrix network, with the Riot app'!!!!!   It's a positive, unified dev' team, that's not trying to herd meercats, corporate fat-cats, or  lemmings.

It's already mature, and all that XMPP should have been.  The IRC "bridges" (like gateways) actually work, and there's bridges to XMPP and other legacy networks, too.  

No relying on third party web-chat providers that disappear, like the defunct jappix (dot) com.  The dev' team has their OWN web-chat, for guests to try, before getting the Riot app'.  

Here's the Network's chan':  
https://matrix.to/#/#matrix:matrix.org

You can join other chan's from there, plenty bridged to IRC.  And the directory is for all rooms that the admins list on the entire network ecosystem.  So much for "standalone silos"!!!!!!

The Directory search will show the Riot app' room.  You can also:  /join #riot:matrix.org
(Yeah, some IRC commands work), or:
https://matrix.to/#/#riot:matrix.org

You don't get much simpler than, "Here's the link.  It just works, plain and simple!"

It's already everything XMPP should have been!!!

**Comment by locutis-of-borg-1999** [comment]
Oh, those links offer options for clients...  

I meant to drop the direct web-client link for Riot, in the Matrix & Riot rooms.  
Here:
    https://riot.im/app/#/room/#matrix:matrix.org   

    https://riot.im/app/#/room/#riot:matrix.org    

Oh, I also, I did try one last time to find an easy way to introduce people to XMPP, and found a LOT of frustrating dead-ends, dead links and things NOT for new folks, or federated FOSS.  
I DID learn that CERN dumped XMPP.  They HAD an XMPP web-chat.  Not any more.  And they are VERY supportive of FOSS.  

Anyway, I hope this helps someone else who might have got stuck in the quagmire.

**Comment by guusdk** [comment]
Added super-simple "getting started" page in #246

**Comment by guusdk** [comment]
Merged #246
