### ISSUE TITLE
The blog Atom feed is not valid

### ISSUE THREAD

**Issue by edhelas** [xsf/xmpp.org#601]
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fxmpp.org%2Ffeeds%2Fall.atom.xml

**Comment by wurstsalat3000** [comment]
Probably related to #718

**Comment by wurstsalat3000** [comment]
From [the docs](https://docs.getpelican.com/en/stable/settings.html#feed-settings):

> The domain prepended to feed URLs. Since feed URLs should always be absolute, it is highly recommended to define this (e.g., “https://feeds.example.com”). If you have already explicitly defined SITEURL (see above) and want to use the same domain for your feeds, you can just set: FEED_DOMAIN = SITEURL.

**Comment by Echolon** [comment]
Anyone has a suggestion what exactly needs to be done?

**Comment by wurstsalat3000** [comment]
The validator still complains about a duplicated `guid` in `<guid>https://xmpp.org/2008/11/xmpp-roundup/</guid>`. I'll see how to fix that.
