### ISSUE TITLE
Newsletter link problem from 2019 (31 january)

### ISSUE THREAD

**Issue by Neustradamus** [xsf/xmpp.org#638]
Recall about the problem of link:
-> https://xmpp.org/2019/01/the-xmpp-newsletter-31-january-2018/

Ten month already, maybe forgotten.

Linked to:
- https://github.com/xsf/xmpp.org/issues/532

**Comment by horazont** [comment]
@Neustradamus Do *not* create new issues for things which have already been closed unless has changed.

Time passing is not something which has changed.

Commenting on the old ticket should be preferred over creating a new one.

I like to borrow what jcbrand has said: Nobody cares enough to fix it. The affected page is a newsletter page from nearly a year ago. Nobody cares anymore (if anyone cared ever) about how the URL looks.

Stop spamming this tracker.
