### ISSUE TITLE
There is a difference between Microsoft and Windows

### ISSUE THREAD

**Issue by marc7636** [xsf/xmpp.org#640]
On the main webpage (xmpp.org) there has been used a Microsoft logo to represent Windows, instead of using the Windows logo to represent Windows. I know this is a nitpick, but it is an easy fix.

**Comment by Nyco** [comment]
Thanks for the report.

What page(s)?
Can you please provide the correct logo? A PR could help as well.

**Comment by wurstsalat3000** [comment]
![Screenshot_20200716_092342-1](https://user-images.githubusercontent.com/35428560/87639922-4192cf80-c746-11ea-8f8a-bdf24fbee4ae.png)

That’s the Microsoft logo. The Windows logo can be found [here](https://de.wikipedia.org/wiki/Microsoft_Windows).

I wouldn’t change it though. Looking at both Apple (not spcifically MacOS/iOS) and Linux (generic Tux) logos, I’d say it’s more about recognizability.
