### ISSUE TITLE
xmpp.com search results and redirections

### ISSUE THREAD

**Issue by sonnyp** [xsf/xmpp.org#651]
xmpp.com/ redirects to xmpp.org/
However it's not the case for https://xmpp.com/extensions/ (as well as `/extensions/*` ) and maybe others.

As such `xmpp.com` URLs are showing up in search engine results.

Example: https://www.google.com/search?q=conversation+xep+0385&oq=conversation+xep+0385

yields https://xmpp.com/extensions/xep-0423.html

It presents several inconvenients:
1. The certificate is invalid
2. Confusing
3. Not ideal for indexing

**Comment by guusdk** [comment]
Ah, thanks for bringing that up. Am I right to conclude that a redirect on our website would fix this sufficiently?

**Comment by sonnyp** [comment]
The same permanent redirect that is applied to xmpp.com/* should work fine.

**Comment by sonnyp** [comment]
Hmmm actually that redirect won't work out of the box with the current certificate on https://xmpp.com 

The certificate should be fixed first

**Comment by Ppjet6** [comment]
That doesn't seem to be something we handle in this repo (the Dockerfile is pretty simple), it's probably handled in the reverse proxy directly on the server.

I guess something like the following would do, but @mwild1 would know better.

```nginx
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name xmpp.com;
    include /path/to/ssl.conf;
    return 301 https://xmpp.org$request_uri;
}
```

**Comment by Neustradamus** [comment]
It is possible to solve the problem of the newsletter too?
One year soon:
- https://github.com/xsf/xmpp.org/issues/532
- https://github.com/xsf/xmpp.org/issues/638

**Comment by guusdk** [comment]
![tenor](https://user-images.githubusercontent.com/4253898/70471086-ce98ea80-1acc-11ea-8d66-ed028ee8c02a.gif)

**Comment by Echolon** [comment]
@guusdk can you explain or suggest what a possible action here would be?
