### ISSUE TITLE
Provide bio for council (Daniel)

### ISSUE THREAD

**Issue by guusdk** [xsf/xmpp.org#654]
Hi @iNPUTmice  - welcome on the XSF Council! Our website lists every member of the council with a small bio. Please provide yours at: https://github.com/xsf/xmpp.org/blob/master/content/pages/about/xmpp-standards-foundation.md#the-council

**Comment by guusdk** [comment]
As you've been on Council before, we still have an old bio in git history.

>  __Daniel Gultsch__ is the maintainer of the Android client [Conversations](https://conversations.im) and operates an [XMPP domain hosting service](https://account.conversations.im/domain). He has also (co-) created several XEPs. Contact information can be found on [his website](https://gultsch.de).

Feel free to re-use or improve :)

**Comment by iNPUTmice** [comment]
The old bio is fine for now. Thank you @guusdk
