### ISSUE TITLE
Release dates in tables libraries and servers

### ISSUE THREAD

**Issue by agnauck** [xsf/xmpp.org#66]
I suggest to remove the release dates in those tables.
Some of the dates are wrong right now. And it would be hard for us to maintain all this dates.
We should not give a visitor the impression that a software is outdated only because we missed updating the dates.

**Comment by imaginator** [comment]
I agree. And I'd suggest we change to "is maintained" (commits in the last year and bug fixes) for inclusion in the list.

Would also be nice to have the project names as URLs and get rid of the seperate URL field... 

pull requests welcomed ;)

**Comment by agnauck** [comment]
a software can still be maintained without having a commit or bug fix. Active support also through the community for example.

There are many libraries out there which had no commits for a long time, they just work as is and no bugs were reported. I still would consider them as "is maintained"

ya, its on my TODO list to send pull requests.

**Comment by imaginator** [comment]
Totally right about active support. I just remember seeing something on there and thinking... that's definitely dead. Can't remember what it was now.

**Comment by imaginator** [comment]
Similar to #78
