### ISSUE TITLE
Fork legastero/memberbot under the XSF umbrella

### ISSUE THREAD

**Issue by Neustradamus** [xsf/xmpp.org#665]
The XSF memberbot source code is always missing in this XSF GitHub.

@legastero: Lance can you move your archived repository to XSF place?

Thanks in advance and thanks again and again (a new time to tell) for your bot.

**Comment by Ppjet6** [comment]
The code for memberbot currently resides at https://github.com/legastero/memberbot.

**Comment by Neustradamus** [comment]
The repository has been archived several years ago.

We have already talked to add the code here, please do not closed a ticket not solved.

**Comment by Ppjet6** [comment]
I renamed the issue to make it reflect what you meant.

@mwild1, I don't have enough powers to do that, could you have a look?

**Comment by agnauck** [comment]
I think @linkmauve made some improvements and we should fork from his for ;-)
https://github.com/linkmauve/memberbot

**Comment by Neustradamus** [comment]
If @legastero can move the repository here, it will be better and after it, easy to add changes from @linkmauve and add my PR after it.

**Comment by mwild1** [comment]
https://github.com/xsf/memberbot

**Comment by Neustradamus** [comment]
Why a fork and not a move from legastero/memberbot?

**Comment by agnauck** [comment]
> Why a fork and not a move from legastero/memberbot?

because you asked us to fork it. Look at the title of this issue which you created

**Comment by Neustradamus** [comment]
I have never requested to fork, I have requested a move ;)

**Comment by Ppjet6** [comment]
Alex (as the secretary) deploys memberbot himself, he could be using his own fork for all it's worth. Does it matter that the repository is moved? Who cares?

**Comment by Neustradamus** [comment]
@legastero: https://help.github.com/articles/about-repository-transfers/

Thanks in advance.

**Comment by Ppjet6** [comment]
On 2020/01/31, Neustradamus wrote:
> https://help.github.com/articles/about-repository-transfers/

I'm not asking about the feasability of the thing. I'm asking about the
usefulness.

-- 
Maxime “pep” Buquet
