### ISSUE TITLE
Memberbot : Problem with the choices

### ISSUE THREAD

**Issue by Neustradamus** [xsf/xmpp.org#666]
I have already informed, but for have a trace:
- When we select "Yes", it is yes, no problem
- When we select "No", the choice is not accepted because it is not "no", it is "No"

I think that this problem is to have always "yes" instead of "no".

Information: XMPP clients used:
- Psi / Psi+ with an enabled function: Options -> Messages -> Input -> Automatically capitalize the first letter in a sentence

**Comment by Ppjet6** [comment]
Wrong repository.
