### ISSUE TITLE
Remove Google's APIs and other google assets from xmpp.org (privacy reasons)

### ISSUE THREAD

**Issue by DontUseGithub** [xsf/xmpp.org#694]
It's deeply saddening that xmpp.org is relying on google's assets, since we all know very well how privacy-invasive Google is and how little they care about us having an open internet. They wanna censor and control as much of the internet as they can.

**Comment by guusdk** [comment]
Please don't use our repository as your soapbox.

If you want to have a discussion on the usage of GitHub, spamming people with alleged certainty, without even suggesting an alternative or any other positive contribution, is possibly the worst way to start.

**Comment by jcbrand** [comment]
The xmpp.org team is understaffed and overworked, so on a different day I might have reacted the same way as @guusdk. 

That said, I had a quick look and thought it wouldn't be much effort to host the Google assets under xmpp.org.

I've made a PR for this.

**Comment by DontUseGithub** [comment]
Thank you very much @jcbrand and sorry everyone for my 'wrongdoings'.

**Comment by jcbrand** [comment]
It's OK @DontUseGithub, my suggestion would be to write in a more neutral way and to not use emotional or moralistic language.
