### ISSUE TITLE
Memberbot repository has not "Issues" enabled section

### ISSUE THREAD

**Issue by Neustradamus** [xsf/xmpp.org#711]
Can you add "Issues" in Memberbot repository?
- https://github.com/xsf/memberbot/

The originaly project and source:
- https://github.com/legastero/memberbot

Thanks in advance.

**Comment by Echolon** [comment]
@agnauck may you have a look a this, too?

**Comment by agnauck** [comment]
I do not have access to change settings in the repo.
@mwild1 can you help here?

**Comment by Neustradamus** [comment]
Good news after a long time, it is here:
- https://github.com/xsf/memberbot/issues

**Comment by Echolon** [comment]
Ok, then I will close this.
