### ISSUE TITLE
WARNING: Feeds generated without SITEURL set properly may not be valid

### ISSUE THREAD

**Issue by Zash** [xsf/xmpp.org#718]
[The Atom feed is apparently malformed](https://logs.xmpp.org/xsf/2020-06-11?p=h#2020-06-11-5fb24ea7898f1683)

[There's even a warning in the build output about it](https://travis-ci.org/github/xsf/xmpp.org/jobs/697232984#L224)

Probably about this line:

https://github.com/xsf/xmpp.org/blob/efd11e6306662b93b3a0a7fa42a6c406655cbeff/pelicanconf.py#L9

**Comment by wurstsalat3000** [comment]
Shouldn’t this be SITEURL rather than SITE_URL ?
