### ISSUE TITLE
need current link for jdev chatlogs

### ISSUE THREAD

**Issue by imaginator** [xsf/xmpp.org#73]
jdev logs point at outdated: http://logs.jabber.org/jdev@conference.jabber.org/

we need this updated to the new logs wherever they are at https://github.com/xsf/xmpp.org/blob/master/content/pages/community/chat.md

Ralph/peter: @intosi might know something about this.

**Comment by guusdk** [comment]
Currently, logs are made available here: http://logs.xmpp.org/

Is there a need to integrate this with the pre-existing http://logs.jabber.org site?

**Comment by intosi** [comment]
jdev is hosted by the friendly jabber.org admins, who will look into this and restore archive access.  There will be a gap in the logs for sure.

**Comment by wurstsalat3000** [comment]
Since jdev is now hosted on @muc.xmpp.org, and the logs are available on http://logs.xmpp.org/ , can this issue be closed?

**Comment by Echolon** [comment]
@imaginator
