### ISSUE TITLE
Font is too small on Windows systems

### ISSUE THREAD

**Issue by wrooot** [xsf/xmpp.org#732]
It was ok before, but a few releases back it was changed to a very small font. Yeah, i can zoom in, but there is so much white space on its page and headings are so huge. Looks jarring.

**Comment by Echolon** [comment]
Hi,

thanks for reporting. Can you make a screenshot please?

**Comment by wrooot** [comment]
It seems that this smaller font is used throughout the whole site now, not just newsletter. This is how it appears for me (tried on various systems and browsers, it looks the same)
![image](https://user-images.githubusercontent.com/7195609/87571686-19b65400-c6d3-11ea-9f1e-59f1c4799978.png)

**Comment by wrooot** [comment]
Correction - various Windows systems. On Linux it has a bigger font
![image](https://user-images.githubusercontent.com/7195609/87572104-b8db4b80-c6d3-11ea-8cee-c2cd802b66fe.png)

**Comment by Echolon** [comment]
@horazont @Zash do you have any suggestions?

**Comment by wurstsalat3000** [comment]
@wrooot you could compare the installed fonts on both systems. The text renders using on the the following: "Helvetica Neue",Helvetica,Roboto,Arial,sans-serif

**Comment by Echolon** [comment]
@wrooot have you found time to review?

**Comment by wrooot** [comment]
Not sure what i should review. On Windows i only see Arial in fonts menu, and from the looks it seems like Arial is being used on Windows. And Arial usually looks smaller. I'm not that familiar with Linux, on Ubuntu i can't find any mentioned font in fc-list output. But it doesn't look like Arial.

**Comment by wurstsalat3000** [comment]
@wrooot I’m sorry, I misinterpreted the CSS. For the text you show here, `'Merriweather', serif` is set with `font-size: 16px`. You could check in your browser’s inspection window which style gets computed on Windows.

**Comment by wrooot** [comment]
I see the same in Firefox Inspector (Merriweather, serif and 16px font-size).

**Comment by wurstsalat3000** [comment]
Is it the same machine you’re viewing the page with on Windows/Linux? Any UI scaling involved? Did you reset the website’s zoom (Ctrl+0)?

**Comment by wrooot** [comment]
I don't have dual boot to test on the same machine. But i have Windows and Ubuntu VMs, which both use 1024x768 resolution, 100% zoom in both browsers. Both using Firefox (though on Windows same is with Chromium Edge).
![image](https://user-images.githubusercontent.com/7195609/94445849-9b852c00-01b0-11eb-8eae-fc249972fc73.png)

**Comment by wurstsalat3000** [comment]
@wrooot I can reproduce this when comparing fonts on Windows/Linux. For me, it’s actually an issue of two different fonts used for rendering. You can check for yourself in Firefox Inspector > Computed Styles > Fonts Tab > Used font (for list element).

**Comment by agnauck** [comment]
Can confirm this as well. The font is smaller on Windows, and also a different type of font series is used on Windows.

**Comment by wrooot** [comment]
Yes, it is using Arial on Windows. Which i don't mind that much, although Arial looks worse. But it also then becomes much smaller. 
![image](https://user-images.githubusercontent.com/7195609/94451773-7a740980-01b7-11eb-946b-6d31963496c2.png)

**Comment by wrooot** [comment]
Thanks you. Just received new newsletter notification and the font is much better now :)

**Comment by Echolon** [comment]
Good to know ☺
