### ISSUE TITLE
Settle on tagline / strapline

### ISSUE THREAD

**Issue by stpeter** [xsf/xmpp.org#75]
We need to settle on the homepage tagline / strapline. Current it reads:

"The most secure messaging standard"

Is that what we agree to use for launch?

**Comment by guusdk** [comment]
Currently, the landing page on the website has:

> The most secure messaging standard
> Battle-tested. Independent. Privacy-focused.

There appears to have been no movement on this issue since it was created. I'm closing this issue as the lack of activity appears to indicate a missing need for further work. Feel free to reopen when needed.
