### ISSUE TITLE
Newsletter Issue Template: Contribution tips may not work

### ISSUE THREAD

**Issue by vanitasvitae** [xsf/xmpp.org#753]
The description of the latest newsletter states that contributors may contribute by doing the following:

> You don't need a command-line tool or any knowledge of git to commit your changes. Just add your comment as follows: Click the Files changed ribbon, then the three dots on the top right, then Edit file. Finally add you comment. Of course, pull requests are appreciated.

I think this may not work for any user, as it requires write access (afaik).
A better, more robust description may be appreciated.

@Echolon

**Comment by Echolon** [comment]
@vanitasvitae I updated the explanation with a new simple offer. Are you okay, with this? Let's discuss in the MUC. I will close this. Thanks for reminding!

https://github.com/xsf/xmpp.org/pull/730
