### ISSUE TITLE
Incomplete listing of officers

### ISSUE THREAD

**Issue by ralphm** [xsf/xmpp.org#771]
We have a [XSF People page](https://xmpp.org/about/xsf/people.html) that is currently a partial overview of the XSF's officers. It now lists Peter as ED an Alex as Secretary. For Peter, the [XSF Members page](https://xmpp.org/about/xsf/members) also links to this page with that role. I see the following points of improvement:

- Remove Peter as ED from both pages. He hasn't served in this role for a number of years now and the position is vacant. We should either note the position as vacant on the People page, or remove the section on the People page for now.
- List all Officers as defined in our [Bylaws](https://xmpp.org/about/xsf/bylaws), article VI. Currently missing are the Treasurer and Chair officer roles, while our [about page](https://xmpp.org/about/xmpp-standards-foundation.html) does point to the People page for former. We could possibly reuse the text for Peter.
- Explicitly list officer roles on the Members page.

**Comment by agnauck** [comment]
created a draft PR here: #781 
Feedback is welcome
