### ISSUE TITLE
Libraries / Clients / Server pages project links

### ISSUE THREAD

**Issue by lloydwatkin** [xsf/xmpp.org#78]
The URLs on these pages (even if we use `rel="nofollow` on them).

Additionally several links are simply the word 'Website' or a link to the host but not the project (e.g. github.com). 

Here's a screenshot to demonstrate:

![screenshot from 2015-11-09 17 10 08](https://cloud.githubusercontent.com/assets/271622/11040542/c077e20e-8704-11e5-85f4-70f128fc03cd.png)

**Comment by stpeter** [comment]
It also seems that the domain names are not clickable.

**Comment by imaginator** [comment]
First phase of updating: https://github.com/xsf/xmpp.org/commit/39acba44f264a4b1ade1f4504cc95ebb195451ae

to do: servers and libraries.
