### ISSUE TITLE
Missing icons/images on wiki.xmpp.org

### ISSUE THREAD

**Issue by Neustradamus** [xsf/xmpp.org#888]
Missing icons/images on wiki.xmpp.org:

Examples:

1/ Blank space after http/https links in wiki.xmpp.org, example on homepage:
- https://wiki.xmpp.org/
- after "HTML"
- after "XMPP" and "Jabber"
- after "LinkedIn"

2/ After an XMPP address

3/ https://wiki.xmpp.org/web/resources/assets/poweredby_mediawiki_88x31.png

4/ https://wiki.xmpp.org/web/resources/assets/licenses/cc-by-sa.png

5/ ...

**Comment by Zash** [comment]
Fixed.

**Comment by Neustradamus** [comment]
@Zash: Thanks for this very fast correction!
