### ISSUE TITLE
Remove need for .html extension from URLs

### ISSUE THREAD

**Issue by adambrault** [xsf/xmpp.org#9]
Presently, all page URLs end with .html

It's possible to get URLs that end without .html through changes to pelican's configuration.

Compare the [present XSF configuration](https://github.com/xsf/xmpp.org/blob/master/pelicanconf.py#L23-L32):

```
ARTICLE_PATHS = [ 'posts/blog', 'posts/learn' ]
ARTICLE_URL = 'posts/{blog_id}/{date:%Y}/{date:%b}/{date:%d}/{slug}'
ARTICLE_SAVE_AS = 'posts/{blog_id}/{date:%Y}/{date:%b}/{date:%d}/{slug}.html'

INDEX_SAVE_AS = 'posts/blog/index.html'
...
YEAR_ARCHIVE_SAVE_AS = 'posts/blog/{date:%Y}/index.html'
```

with [my own site's pelican configuration](https://github.com/adambrault/adambrault.com/blob/master/pelicanconf.py#L50-L59):

```
PAGE_URL = '{slug}'
PAGE_SAVE_AS = '{slug}/index.html'

CATEGORY_URL = '{slug}'
CATEGORY_SAVE_AS = '{slug}/index.html'

YEAR_ARCHIVE_SAVE_AS = '{date:%Y}/index.html'
MONTH_ARCHIVE_SAVE_AS = '{date:%Y}/{date:%m}/index.html'
DAY_ARCHIVE_SAVE_AS = '{date:%Y}/{date:%m}/{date:%d}/index.html'
```

**Comment by adambrault** [comment]
Scratch that. I've apparently checked out the wrong branch? I note that new.xmpp.org already has this kind of setup working.

**Comment by adambrault** [comment]
Alright, this is terribly confusing. When running locally on the master branch, it does not work the way it's currently working on new.xmpp.org.

**Comment by adambrault** [comment]
Closing. :) It *must* be set up to rewrite...

**Comment by imaginator** [comment]
@adambrault just looking through this... The server is currently Github Pages.
