### ISSUE TITLE
Content duplication in about/overview and about/features-and-benefits

### ISSUE THREAD

**Issue by ge0rg** [xsf/xmpp.org#90]
The two pages under http://new.xmpp.org/about/overview and http://new.xmpp.org/about/features-and-benefits share large parts of the content, and look like only one of them should be kept.

I'm not quite sure which one should make it or how to merge them.

**Comment by imaginator** [comment]
You are right. Also http://new.xmpp.org/about/overview is, while a very
valuable page, quickly becoming a wall-o-text.

On 10 November 2015 at 11:28, Georg Lukas <notifications@github.com> wrote:

> The two pages under http://new.xmpp.org/about/overview and
> http://new.xmpp.org/about/features-and-benefits share large parts of the
> content, and look like only one of them should be kept.
>
> I'm not quite sure which one should make it or how to merge them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xsf/xmpp.org/issues/90>.
>



-- 
Simon Tennant | CEO Buddycloud <http://buddycloud.com> | +49 17 8545 0880 |
Meet <https://calendly.com/simon-tennant/buddycloud-call>

**Comment by adambrault** [comment]
@imaginator overview is taken from about 5 pages on the old site. I didn't want us to throw all of that away if someone thought we should keep it so I merged it all here, knowing we could iterate from it. @stpeter had discussed writing a simple intro to XMPP and I thought this might serve as a holding place (and overly long outline) for what he (or someone else) might do with it

**Comment by adambrault** [comment]
@ge0rg you're totally right. I actually think we could merge all of the overview into features and benefits and drop overview entirely for now

**Comment by stpeter** [comment]
What @adambrault and @ge0rg propose works for me. I noticed the wall of text last night, too!

**Comment by bear** [comment]
fixed - the content of features-and-benefits all existed within the overview page so I removed the page and adjusted the sub-menu
