### ISSUE TITLE
Main page semi broken

### ISSUE THREAD

**Issue by Luca-Ziesler** [xsf/xmpp.org#901]
For whatever reason the Windows "Logo" on the main page is broken (won't load)

Both on desktop and smartphone for me

It's in the "Software for every platform
and libraries for every language"
section

Can somebody fix this, or is the website a github pages site and I can just make a pull request? 😄

Thanks anyways

**Comment by Luca-Ziesler** [comment]
nvm

I found the website is hosted via github pages

will do a pull request soon

**Comment by Echolon** [comment]
@Devnol yes thanks, somehow I failed on the svg conversion. Do you have time and motivation to try your luck with creating a proper svg?

**Comment by Echolon** [comment]
actually its related to #890 

I will close this issue - lets discuss in the PR

If anyone knows how to do it I would appreciate as Im not techsavy on this

**Comment by Devnol** [comment]
I made pull #907 which should resolve the issue for good. It should also be good to close #890 once #907 is pushed to master.
