### ISSUE TITLE
Broken links from site's ATOM feeds.

### ISSUE THREAD

**Issue by maranda** [xsf/xmpp.org#979]
Apparently https://xmpp.org/feeds/all.atom.xml does contain some links that lead to unexistant pages, I catched three of 'em today:
- https://xmpp.org/2010/07/xmpp-summit-#9-preview/
- https://xmpp.org/2009/04/mxm-#2/
- https://xmpp.org/2008/01/devcon-#4/

**Comment by wurstsalat3000** [comment]
Thanks! Should be fixed once 5fd29ec82bfd60d9ae41747de1d5a486248a8b5d is deployed.
