### ISSUE TITLE
A lot of versions of XEP are missing

### ISSUE THREAD

**Issue by Neustradamus** [xsf/xmpp.org#980]
It is possible to add all missing version of XEP?

Thanks in advance.

Example (not only one):
- https://github.com/processone/ejabberd/issues/3676#issuecomment-921277619

Linked to:
- https://github.com/xsf/xep-attic/issues/3

**Comment by wurstsalat3000** [comment]
This belongs to xsf/xep-attic or xsf/xeps. There is nothing we can do from here.
