### ISSUE TITLE
All the library links are broken

### ISSUE THREAD

**Issue by xnyhps** [xsf/xmpp.org#99]
Whoever copied https://xmpp.org/xmpp-software/libraries/ to http://new.xmpp.org/software/libraries copied the text of the links instead of the href of the links, so there are many that now refer to just "http://github.com" or "http://website".

**Comment by imaginator** [comment]
yes - I spent about an hour going through and tried to fix many of these. Many of the links were also non-valid.

More work needed.

**Comment by intosi** [comment]
Is this resolved?

**Comment by guusdk** [comment]
Mostly fixed in https://github.com/xsf/xmpp.org/pull/137

**Comment by guusdk** [comment]
I'm closing this issue, as most problems were addressed. Let's create new issues for remaining problems when we find them.
