### ISSUE TITLE
Multilingual site: Do we want this?

### ISSUE THREAD

**Issue by Echolon** [xsf/xmpp.org#994]
Hi,

just a discussion if we wanna go down to a multi-lingual site with the new Hugo setup.

It could be very nice for specific pages but also for the Newsletter hosting.

@wurstsalat3000

**Comment by wurstsalat3000** [comment]
See 2b384c0fbe08690e278c02adfd51ee392c2a6dd3

Pages are now ready for translations.

Naming convention would be `example_post.md`, `example_post.de.md`, `example_post.fr.md` etc. to link translated pages to the original post.

**Comment by Echolon** [comment]
Many thanks!!
